//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecoporto.CRM.Site.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.1.50.4:5456/Criptografia.asmx")]
        public string Ecoporto_CRM_Site_WsControleSenha_Criptografia {
            get {
                return ((string)(this["Ecoporto_CRM_Site_WsControleSenha_Criptografia"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://srv0019:5040/wsexterno/Service1.asmx")]
        public string Ecoporto_CRM_Site_WsConsultaClientes_Service1 {
            get {
                return ((string)(this["Ecoporto_CRM_Site_WsConsultaClientes_Service1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.1.50.4:3567/ws.asmx")]
        public string Ecoporto_CRM_Site_WsSPC_Ws {
            get {
                return ((string)(this["Ecoporto_CRM_Site_WsSPC_Ws"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.1.50.4:3289/SimuladorCalculo.asmx")]
        public string Ecoporto_CRM_Site_WsSimulador_SimuladorCalculo {
            get {
                return ((string)(this["Ecoporto_CRM_Site_WsSimulador_SimuladorCalculo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute(" http://10.1.50.4:3289/IntegraChronos.asmx ")]
        public string Ecoporto_CRM_Site_WsIntegraChronos_IntegraChronos {
            get {
                return ((string)(this["Ecoporto_CRM_Site_WsIntegraChronos_IntegraChronos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://srv0019:2530/Calcular.asmx")]
        public string Ecoporto_CRM_Site_WsCalculo_Calcular {
            get {
                return ((string)(this["Ecoporto_CRM_Site_WsCalculo_Calcular"]));
            }
        }
    }
}
