//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsSimuladorCalculoTabelas.WSUnico {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusNfe", Namespace="http://tecondi.com.br/services/nfe")]
    public enum StatusNfe : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AguardandoProcessamento = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AguardandoEnvioPrefeitura = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AguardandoProcessamentoSAP = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Processado = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErroProcessamentoPrefeitura = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cancelada = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AguardandoRetornoPrefeitura = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AguardandoCancelamentoPrefeitura = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AguardandoCancelamentoSapiens = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AguardandoCancelamentoChronos = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AguardandoBaixaTituloSapiens = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AguardandoCancelamentoPorSubstituicao = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotaFiscalInexistente = 12,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tecondi.com.br/services/nfe", ConfigurationName="WSUnico.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tecondi.com.br/services/nfe/CancelaNotaFiscalDeVenda", ReplyAction="*")]
        WsSimuladorCalculoTabelas.WSUnico.StatusNfe CancelaNotaFiscalDeVenda(long fatId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tecondi.com.br/services/nfe/CancelaNotaFiscalDeVenda", ReplyAction="*")]
        System.Threading.Tasks.Task<WsSimuladorCalculoTabelas.WSUnico.StatusNfe> CancelaNotaFiscalDeVendaAsync(long fatId);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento xmlSapiens no namespace http://tecondi.com.br/services/nfe não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tecondi.com.br/services/nfe/GeraNotaFiscalDeVendaSAP", ReplyAction="*")]
        WsSimuladorCalculoTabelas.WSUnico.GeraNotaFiscalDeVendaSAPResponse GeraNotaFiscalDeVendaSAP(WsSimuladorCalculoTabelas.WSUnico.GeraNotaFiscalDeVendaSAPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tecondi.com.br/services/nfe/GeraNotaFiscalDeVendaSAP", ReplyAction="*")]
        System.Threading.Tasks.Task<WsSimuladorCalculoTabelas.WSUnico.GeraNotaFiscalDeVendaSAPResponse> GeraNotaFiscalDeVendaSAPAsync(WsSimuladorCalculoTabelas.WSUnico.GeraNotaFiscalDeVendaSAPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tecondi.com.br/services/nfe/ProcessarFilaDeNotas")]
        void ProcessarFilaDeNotas();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tecondi.com.br/services/nfe/ProcessarFilaDeNotas")]
        System.Threading.Tasks.Task ProcessarFilaDeNotasAsync();
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento GeraNotasDiariaResult no namespace http://tecondi.com.br/services/nfe não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tecondi.com.br/services/nfe/GeraNotasDiaria", ReplyAction="*")]
        WsSimuladorCalculoTabelas.WSUnico.GeraNotasDiariaResponse GeraNotasDiaria(WsSimuladorCalculoTabelas.WSUnico.GeraNotasDiariaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tecondi.com.br/services/nfe/GeraNotasDiaria", ReplyAction="*")]
        System.Threading.Tasks.Task<WsSimuladorCalculoTabelas.WSUnico.GeraNotasDiariaResponse> GeraNotasDiariaAsync(WsSimuladorCalculoTabelas.WSUnico.GeraNotasDiariaRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento obsNf no namespace http://tecondi.com.br/services/nfe não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tecondi.com.br/services/nfe/SubstituirNFSe", ReplyAction="*")]
        WsSimuladorCalculoTabelas.WSUnico.SubstituirNFSeResponse SubstituirNFSe(WsSimuladorCalculoTabelas.WSUnico.SubstituirNFSeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tecondi.com.br/services/nfe/SubstituirNFSe", ReplyAction="*")]
        System.Threading.Tasks.Task<WsSimuladorCalculoTabelas.WSUnico.SubstituirNFSeResponse> SubstituirNFSeAsync(WsSimuladorCalculoTabelas.WSUnico.SubstituirNFSeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GeraNotaFiscalDeVendaSAPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GeraNotaFiscalDeVendaSAP", Namespace="http://tecondi.com.br/services/nfe", Order=0)]
        public WsSimuladorCalculoTabelas.WSUnico.GeraNotaFiscalDeVendaSAPRequestBody Body;
        
        public GeraNotaFiscalDeVendaSAPRequest() {
        }
        
        public GeraNotaFiscalDeVendaSAPRequest(WsSimuladorCalculoTabelas.WSUnico.GeraNotaFiscalDeVendaSAPRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tecondi.com.br/services/nfe")]
    public partial class GeraNotaFiscalDeVendaSAPRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long fatId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string xmlSapiens;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string obsNf;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string xmlSAP;
        
        public GeraNotaFiscalDeVendaSAPRequestBody() {
        }
        
        public GeraNotaFiscalDeVendaSAPRequestBody(long fatId, string xmlSapiens, string obsNf, string xmlSAP) {
            this.fatId = fatId;
            this.xmlSapiens = xmlSapiens;
            this.obsNf = obsNf;
            this.xmlSAP = xmlSAP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GeraNotaFiscalDeVendaSAPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GeraNotaFiscalDeVendaSAPResponse", Namespace="http://tecondi.com.br/services/nfe", Order=0)]
        public WsSimuladorCalculoTabelas.WSUnico.GeraNotaFiscalDeVendaSAPResponseBody Body;
        
        public GeraNotaFiscalDeVendaSAPResponse() {
        }
        
        public GeraNotaFiscalDeVendaSAPResponse(WsSimuladorCalculoTabelas.WSUnico.GeraNotaFiscalDeVendaSAPResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tecondi.com.br/services/nfe")]
    public partial class GeraNotaFiscalDeVendaSAPResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GeraNotaFiscalDeVendaSAPResult;
        
        public GeraNotaFiscalDeVendaSAPResponseBody() {
        }
        
        public GeraNotaFiscalDeVendaSAPResponseBody(string GeraNotaFiscalDeVendaSAPResult) {
            this.GeraNotaFiscalDeVendaSAPResult = GeraNotaFiscalDeVendaSAPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GeraNotasDiariaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GeraNotasDiaria", Namespace="http://tecondi.com.br/services/nfe", Order=0)]
        public WsSimuladorCalculoTabelas.WSUnico.GeraNotasDiariaRequestBody Body;
        
        public GeraNotasDiariaRequest() {
        }
        
        public GeraNotasDiariaRequest(WsSimuladorCalculoTabelas.WSUnico.GeraNotasDiariaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GeraNotasDiariaRequestBody {
        
        public GeraNotasDiariaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GeraNotasDiariaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GeraNotasDiariaResponse", Namespace="http://tecondi.com.br/services/nfe", Order=0)]
        public WsSimuladorCalculoTabelas.WSUnico.GeraNotasDiariaResponseBody Body;
        
        public GeraNotasDiariaResponse() {
        }
        
        public GeraNotasDiariaResponse(WsSimuladorCalculoTabelas.WSUnico.GeraNotasDiariaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tecondi.com.br/services/nfe")]
    public partial class GeraNotasDiariaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GeraNotasDiariaResult;
        
        public GeraNotasDiariaResponseBody() {
        }
        
        public GeraNotasDiariaResponseBody(string GeraNotasDiariaResult) {
            this.GeraNotasDiariaResult = GeraNotasDiariaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubstituirNFSeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubstituirNFSe", Namespace="http://tecondi.com.br/services/nfe", Order=0)]
        public WsSimuladorCalculoTabelas.WSUnico.SubstituirNFSeRequestBody Body;
        
        public SubstituirNFSeRequest() {
        }
        
        public SubstituirNFSeRequest(WsSimuladorCalculoTabelas.WSUnico.SubstituirNFSeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tecondi.com.br/services/nfe")]
    public partial class SubstituirNFSeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long fatId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string obsNf;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string xmlSAP;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long rpsSubstituido;
        
        public SubstituirNFSeRequestBody() {
        }
        
        public SubstituirNFSeRequestBody(long fatId, string obsNf, string xmlSAP, long rpsSubstituido) {
            this.fatId = fatId;
            this.obsNf = obsNf;
            this.xmlSAP = xmlSAP;
            this.rpsSubstituido = rpsSubstituido;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubstituirNFSeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubstituirNFSeResponse", Namespace="http://tecondi.com.br/services/nfe", Order=0)]
        public WsSimuladorCalculoTabelas.WSUnico.SubstituirNFSeResponseBody Body;
        
        public SubstituirNFSeResponse() {
        }
        
        public SubstituirNFSeResponse(WsSimuladorCalculoTabelas.WSUnico.SubstituirNFSeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tecondi.com.br/services/nfe")]
    public partial class SubstituirNFSeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SubstituirNFSeResult;
        
        public SubstituirNFSeResponseBody() {
        }
        
        public SubstituirNFSeResponseBody(string SubstituirNFSeResult) {
            this.SubstituirNFSeResult = SubstituirNFSeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : WsSimuladorCalculoTabelas.WSUnico.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<WsSimuladorCalculoTabelas.WSUnico.ServiceSoap>, WsSimuladorCalculoTabelas.WSUnico.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WsSimuladorCalculoTabelas.WSUnico.StatusNfe CancelaNotaFiscalDeVenda(long fatId) {
            return base.Channel.CancelaNotaFiscalDeVenda(fatId);
        }
        
        public System.Threading.Tasks.Task<WsSimuladorCalculoTabelas.WSUnico.StatusNfe> CancelaNotaFiscalDeVendaAsync(long fatId) {
            return base.Channel.CancelaNotaFiscalDeVendaAsync(fatId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WsSimuladorCalculoTabelas.WSUnico.GeraNotaFiscalDeVendaSAPResponse WsSimuladorCalculoTabelas.WSUnico.ServiceSoap.GeraNotaFiscalDeVendaSAP(WsSimuladorCalculoTabelas.WSUnico.GeraNotaFiscalDeVendaSAPRequest request) {
            return base.Channel.GeraNotaFiscalDeVendaSAP(request);
        }
        
        public string GeraNotaFiscalDeVendaSAP(long fatId, string xmlSapiens, string obsNf, string xmlSAP) {
            WsSimuladorCalculoTabelas.WSUnico.GeraNotaFiscalDeVendaSAPRequest inValue = new WsSimuladorCalculoTabelas.WSUnico.GeraNotaFiscalDeVendaSAPRequest();
            inValue.Body = new WsSimuladorCalculoTabelas.WSUnico.GeraNotaFiscalDeVendaSAPRequestBody();
            inValue.Body.fatId = fatId;
            inValue.Body.xmlSapiens = xmlSapiens;
            inValue.Body.obsNf = obsNf;
            inValue.Body.xmlSAP = xmlSAP;
            WsSimuladorCalculoTabelas.WSUnico.GeraNotaFiscalDeVendaSAPResponse retVal = ((WsSimuladorCalculoTabelas.WSUnico.ServiceSoap)(this)).GeraNotaFiscalDeVendaSAP(inValue);
            return retVal.Body.GeraNotaFiscalDeVendaSAPResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WsSimuladorCalculoTabelas.WSUnico.GeraNotaFiscalDeVendaSAPResponse> WsSimuladorCalculoTabelas.WSUnico.ServiceSoap.GeraNotaFiscalDeVendaSAPAsync(WsSimuladorCalculoTabelas.WSUnico.GeraNotaFiscalDeVendaSAPRequest request) {
            return base.Channel.GeraNotaFiscalDeVendaSAPAsync(request);
        }
        
        public System.Threading.Tasks.Task<WsSimuladorCalculoTabelas.WSUnico.GeraNotaFiscalDeVendaSAPResponse> GeraNotaFiscalDeVendaSAPAsync(long fatId, string xmlSapiens, string obsNf, string xmlSAP) {
            WsSimuladorCalculoTabelas.WSUnico.GeraNotaFiscalDeVendaSAPRequest inValue = new WsSimuladorCalculoTabelas.WSUnico.GeraNotaFiscalDeVendaSAPRequest();
            inValue.Body = new WsSimuladorCalculoTabelas.WSUnico.GeraNotaFiscalDeVendaSAPRequestBody();
            inValue.Body.fatId = fatId;
            inValue.Body.xmlSapiens = xmlSapiens;
            inValue.Body.obsNf = obsNf;
            inValue.Body.xmlSAP = xmlSAP;
            return ((WsSimuladorCalculoTabelas.WSUnico.ServiceSoap)(this)).GeraNotaFiscalDeVendaSAPAsync(inValue);
        }
        
        public void ProcessarFilaDeNotas() {
            base.Channel.ProcessarFilaDeNotas();
        }
        
        public System.Threading.Tasks.Task ProcessarFilaDeNotasAsync() {
            return base.Channel.ProcessarFilaDeNotasAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WsSimuladorCalculoTabelas.WSUnico.GeraNotasDiariaResponse WsSimuladorCalculoTabelas.WSUnico.ServiceSoap.GeraNotasDiaria(WsSimuladorCalculoTabelas.WSUnico.GeraNotasDiariaRequest request) {
            return base.Channel.GeraNotasDiaria(request);
        }
        
        public string GeraNotasDiaria() {
            WsSimuladorCalculoTabelas.WSUnico.GeraNotasDiariaRequest inValue = new WsSimuladorCalculoTabelas.WSUnico.GeraNotasDiariaRequest();
            inValue.Body = new WsSimuladorCalculoTabelas.WSUnico.GeraNotasDiariaRequestBody();
            WsSimuladorCalculoTabelas.WSUnico.GeraNotasDiariaResponse retVal = ((WsSimuladorCalculoTabelas.WSUnico.ServiceSoap)(this)).GeraNotasDiaria(inValue);
            return retVal.Body.GeraNotasDiariaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WsSimuladorCalculoTabelas.WSUnico.GeraNotasDiariaResponse> WsSimuladorCalculoTabelas.WSUnico.ServiceSoap.GeraNotasDiariaAsync(WsSimuladorCalculoTabelas.WSUnico.GeraNotasDiariaRequest request) {
            return base.Channel.GeraNotasDiariaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WsSimuladorCalculoTabelas.WSUnico.GeraNotasDiariaResponse> GeraNotasDiariaAsync() {
            WsSimuladorCalculoTabelas.WSUnico.GeraNotasDiariaRequest inValue = new WsSimuladorCalculoTabelas.WSUnico.GeraNotasDiariaRequest();
            inValue.Body = new WsSimuladorCalculoTabelas.WSUnico.GeraNotasDiariaRequestBody();
            return ((WsSimuladorCalculoTabelas.WSUnico.ServiceSoap)(this)).GeraNotasDiariaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WsSimuladorCalculoTabelas.WSUnico.SubstituirNFSeResponse WsSimuladorCalculoTabelas.WSUnico.ServiceSoap.SubstituirNFSe(WsSimuladorCalculoTabelas.WSUnico.SubstituirNFSeRequest request) {
            return base.Channel.SubstituirNFSe(request);
        }
        
        public string SubstituirNFSe(long fatId, string obsNf, string xmlSAP, long rpsSubstituido) {
            WsSimuladorCalculoTabelas.WSUnico.SubstituirNFSeRequest inValue = new WsSimuladorCalculoTabelas.WSUnico.SubstituirNFSeRequest();
            inValue.Body = new WsSimuladorCalculoTabelas.WSUnico.SubstituirNFSeRequestBody();
            inValue.Body.fatId = fatId;
            inValue.Body.obsNf = obsNf;
            inValue.Body.xmlSAP = xmlSAP;
            inValue.Body.rpsSubstituido = rpsSubstituido;
            WsSimuladorCalculoTabelas.WSUnico.SubstituirNFSeResponse retVal = ((WsSimuladorCalculoTabelas.WSUnico.ServiceSoap)(this)).SubstituirNFSe(inValue);
            return retVal.Body.SubstituirNFSeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WsSimuladorCalculoTabelas.WSUnico.SubstituirNFSeResponse> WsSimuladorCalculoTabelas.WSUnico.ServiceSoap.SubstituirNFSeAsync(WsSimuladorCalculoTabelas.WSUnico.SubstituirNFSeRequest request) {
            return base.Channel.SubstituirNFSeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WsSimuladorCalculoTabelas.WSUnico.SubstituirNFSeResponse> SubstituirNFSeAsync(long fatId, string obsNf, string xmlSAP, long rpsSubstituido) {
            WsSimuladorCalculoTabelas.WSUnico.SubstituirNFSeRequest inValue = new WsSimuladorCalculoTabelas.WSUnico.SubstituirNFSeRequest();
            inValue.Body = new WsSimuladorCalculoTabelas.WSUnico.SubstituirNFSeRequestBody();
            inValue.Body.fatId = fatId;
            inValue.Body.obsNf = obsNf;
            inValue.Body.xmlSAP = xmlSAP;
            inValue.Body.rpsSubstituido = rpsSubstituido;
            return ((WsSimuladorCalculoTabelas.WSUnico.ServiceSoap)(this)).SubstituirNFSeAsync(inValue);
        }
    }
}
