//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Ecoporto.CRM.Site.WsSPC {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WsSoap", Namespace="http://tempuri.org/")]
    public partial class Ws : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsultarSPCOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarBancoDeDadosOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Ws() {
            this.Url = global::Ecoporto.CRM.Site.Properties.Settings.Default.Ecoporto_CRM_Site_WsSPC_Ws;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsultarSPCCompletedEventHandler ConsultarSPCCompleted;
        
        /// <remarks/>
        public event ConsultarBancoDeDadosCompletedEventHandler ConsultarBancoDeDadosCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarSPC", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ConsultaSpcResponse ConsultarSPC(string tipoPessoaDocumento, string documento, string usuarioLogado, string hash) {
            object[] results = this.Invoke("ConsultarSPC", new object[] {
                        tipoPessoaDocumento,
                        documento,
                        usuarioLogado,
                        hash});
            return ((ConsultaSpcResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarSPCAsync(string tipoPessoaDocumento, string documento, string usuarioLogado, string hash) {
            this.ConsultarSPCAsync(tipoPessoaDocumento, documento, usuarioLogado, hash, null);
        }
        
        /// <remarks/>
        public void ConsultarSPCAsync(string tipoPessoaDocumento, string documento, string usuarioLogado, string hash, object userState) {
            if ((this.ConsultarSPCOperationCompleted == null)) {
                this.ConsultarSPCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarSPCOperationCompleted);
            }
            this.InvokeAsync("ConsultarSPC", new object[] {
                        tipoPessoaDocumento,
                        documento,
                        usuarioLogado,
                        hash}, this.ConsultarSPCOperationCompleted, userState);
        }
        
        private void OnConsultarSPCOperationCompleted(object arg) {
            if ((this.ConsultarSPCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarSPCCompleted(this, new ConsultarSPCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarBancoDeDados", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ConsultaSpcResponse ConsultarBancoDeDados(string documento, string hash) {
            object[] results = this.Invoke("ConsultarBancoDeDados", new object[] {
                        documento,
                        hash});
            return ((ConsultaSpcResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarBancoDeDadosAsync(string documento, string hash) {
            this.ConsultarBancoDeDadosAsync(documento, hash, null);
        }
        
        /// <remarks/>
        public void ConsultarBancoDeDadosAsync(string documento, string hash, object userState) {
            if ((this.ConsultarBancoDeDadosOperationCompleted == null)) {
                this.ConsultarBancoDeDadosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarBancoDeDadosOperationCompleted);
            }
            this.InvokeAsync("ConsultarBancoDeDados", new object[] {
                        documento,
                        hash}, this.ConsultarBancoDeDadosOperationCompleted, userState);
        }
        
        private void OnConsultarBancoDeDadosOperationCompleted(object arg) {
            if ((this.ConsultarBancoDeDadosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarBancoDeDadosCompleted(this, new ConsultarBancoDeDadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultaSpcResponse {
        
        private int idField;
        
        private StatusAnaliseDeCreditoResponse statusAnaliseDeCreditoField;
        
        private int contaIdField;
        
        private bool restricaoField;
        
        private string condicaoPagamentoField;
        
        private decimal limiteCreditoField;
        
        private TipoPessoaResponse tipoPessoaField;
        
        private System.DateTime dataConsultaField;
        
        private System.DateTime validadeField;
        
        private string protocoloField;
        
        private decimal totalDividaSpcField;
        
        private decimal totalDividaEcoportoField;
        
        private bool inadimplenteSpcField;
        
        private bool inadimplenteEcoportoField;
        
        private int quantidadeField;
        
        private decimal limiteNegociadoField;
        
        private int prazoSolicitadoField;
        
        private bool creditoAprovadoField;
        
        private string razaoSocialField;
        
        private System.Nullable<System.DateTime> fundacaoField;
        
        private string nomeField;
        
        private string nacionalidadeField;
        
        private System.Nullable<System.DateTime> dataNascimentoField;
        
        private string cNPJField;
        
        private string cPFField;
        
        private string atividadeField;
        
        private string situacaoField;
        
        private string logradouroField;
        
        private string bairroField;
        
        private string cidadeField;
        
        private string estadoField;
        
        private int cEPField;
        
        private int protestoQuantidadeField;
        
        private System.Nullable<System.DateTime> protestoDataField;
        
        private System.Nullable<decimal> protestoValorTotalField;
        
        private int acaoQuantidadeField;
        
        private System.Nullable<System.DateTime> acaoDataField;
        
        private System.Nullable<decimal> acaoValorTotalField;
        
        private int pendenciaFinancQuantidadeField;
        
        private System.Nullable<System.DateTime> pendenciaFinancDataField;
        
        private System.Nullable<decimal> pendenciaFinancValorTotalField;
        
        private int participFalenciaQuantidadeField;
        
        private System.Nullable<System.DateTime> participFalenciaDataField;
        
        private System.Nullable<decimal> participFalenciaValorTotalField;
        
        private int spcQuantidadeField;
        
        private System.Nullable<System.DateTime> spcDataField;
        
        private System.Nullable<decimal> spcValorTotalField;
        
        private int chequeSFQuantidadeField;
        
        private System.Nullable<System.DateTime> chequeSFDataField;
        
        private System.Nullable<decimal> chequeSFValorTotalField;
        
        private int chequeSFCCFQuantidadeField;
        
        private System.Nullable<System.DateTime> chequeSFCCFDataField;
        
        private System.Nullable<decimal> chequeSFCCFValorTotalField;
        
        private int chequeLojistaQuantidadeField;
        
        private System.Nullable<System.DateTime> chequeLojistaDataField;
        
        private System.Nullable<decimal> chequeLojistaValorTotalField;
        
        private int chequeCOOutrasQuantidadeField;
        
        private System.Nullable<System.DateTime> chequeCOOutrasDataField;
        
        private System.Nullable<decimal> chequeCOOutrasValorTotalField;
        
        private int consultaRealizadaQuantidadeField;
        
        private System.Nullable<System.DateTime> consultaRealizadaDataField;
        
        private System.Nullable<decimal> consultaRealizadaValorTotalField;
        
        private int alertaDocQuantidadeField;
        
        private System.Nullable<System.DateTime> alertaDocDataField;
        
        private System.Nullable<decimal> alertaDocValorTotalField;
        
        private int creditoConcQuantidadeField;
        
        private System.Nullable<System.DateTime> creditoConcDataField;
        
        private System.Nullable<decimal> creditoConcValorTotalField;
        
        private int contraOrdemQuantidadeField;
        
        private System.Nullable<System.DateTime> contraOrdemDataField;
        
        private System.Nullable<decimal> contraOrdemValorTotalField;
        
        private int contraOrdemDFQuantidadeField;
        
        private System.Nullable<System.DateTime> contraOrdemDFDataField;
        
        private System.Nullable<decimal> contraOrdemDFValorTotalField;
        
        private DetalhesSpcDTO[] detalhesSpcField;
        
        private DetalhesPendenciaFinanceiraDTO[] detalhesPendenciasFinanceirasField;
        
        private DetalhesChequeLojistaDTO[] detalhesChequesLojistasField;
        
        private ContraOrdemDocumentoDiferenteDTO[] detalhesContraOrdemDocumentoDiferenteField;
        
        private ConsultaRealizadaDTO[] detalhesConsultasRealizadasField;
        
        private AlertaDocumentosDTO[] detalhesAlertasDocumentosField;
        
        private CCFDetalhesDTO[] detalhesCCFField;
        
        private string xMLField;
        
        private int usuarioIdField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public StatusAnaliseDeCreditoResponse StatusAnaliseDeCredito {
            get {
                return this.statusAnaliseDeCreditoField;
            }
            set {
                this.statusAnaliseDeCreditoField = value;
            }
        }
        
        /// <remarks/>
        public int ContaId {
            get {
                return this.contaIdField;
            }
            set {
                this.contaIdField = value;
            }
        }
        
        /// <remarks/>
        public bool Restricao {
            get {
                return this.restricaoField;
            }
            set {
                this.restricaoField = value;
            }
        }
        
        /// <remarks/>
        public string CondicaoPagamento {
            get {
                return this.condicaoPagamentoField;
            }
            set {
                this.condicaoPagamentoField = value;
            }
        }
        
        /// <remarks/>
        public decimal LimiteCredito {
            get {
                return this.limiteCreditoField;
            }
            set {
                this.limiteCreditoField = value;
            }
        }
        
        /// <remarks/>
        public TipoPessoaResponse TipoPessoa {
            get {
                return this.tipoPessoaField;
            }
            set {
                this.tipoPessoaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataConsulta {
            get {
                return this.dataConsultaField;
            }
            set {
                this.dataConsultaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Validade {
            get {
                return this.validadeField;
            }
            set {
                this.validadeField = value;
            }
        }
        
        /// <remarks/>
        public string Protocolo {
            get {
                return this.protocoloField;
            }
            set {
                this.protocoloField = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalDividaSpc {
            get {
                return this.totalDividaSpcField;
            }
            set {
                this.totalDividaSpcField = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalDividaEcoporto {
            get {
                return this.totalDividaEcoportoField;
            }
            set {
                this.totalDividaEcoportoField = value;
            }
        }
        
        /// <remarks/>
        public bool InadimplenteSpc {
            get {
                return this.inadimplenteSpcField;
            }
            set {
                this.inadimplenteSpcField = value;
            }
        }
        
        /// <remarks/>
        public bool InadimplenteEcoporto {
            get {
                return this.inadimplenteEcoportoField;
            }
            set {
                this.inadimplenteEcoportoField = value;
            }
        }
        
        /// <remarks/>
        public int Quantidade {
            get {
                return this.quantidadeField;
            }
            set {
                this.quantidadeField = value;
            }
        }
        
        /// <remarks/>
        public decimal LimiteNegociado {
            get {
                return this.limiteNegociadoField;
            }
            set {
                this.limiteNegociadoField = value;
            }
        }
        
        /// <remarks/>
        public int PrazoSolicitado {
            get {
                return this.prazoSolicitadoField;
            }
            set {
                this.prazoSolicitadoField = value;
            }
        }
        
        /// <remarks/>
        public bool CreditoAprovado {
            get {
                return this.creditoAprovadoField;
            }
            set {
                this.creditoAprovadoField = value;
            }
        }
        
        /// <remarks/>
        public string RazaoSocial {
            get {
                return this.razaoSocialField;
            }
            set {
                this.razaoSocialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Fundacao {
            get {
                return this.fundacaoField;
            }
            set {
                this.fundacaoField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string Nacionalidade {
            get {
                return this.nacionalidadeField;
            }
            set {
                this.nacionalidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DataNascimento {
            get {
                return this.dataNascimentoField;
            }
            set {
                this.dataNascimentoField = value;
            }
        }
        
        /// <remarks/>
        public string CNPJ {
            get {
                return this.cNPJField;
            }
            set {
                this.cNPJField = value;
            }
        }
        
        /// <remarks/>
        public string CPF {
            get {
                return this.cPFField;
            }
            set {
                this.cPFField = value;
            }
        }
        
        /// <remarks/>
        public string Atividade {
            get {
                return this.atividadeField;
            }
            set {
                this.atividadeField = value;
            }
        }
        
        /// <remarks/>
        public string Situacao {
            get {
                return this.situacaoField;
            }
            set {
                this.situacaoField = value;
            }
        }
        
        /// <remarks/>
        public string Logradouro {
            get {
                return this.logradouroField;
            }
            set {
                this.logradouroField = value;
            }
        }
        
        /// <remarks/>
        public string Bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        public string Cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
            }
        }
        
        /// <remarks/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public int CEP {
            get {
                return this.cEPField;
            }
            set {
                this.cEPField = value;
            }
        }
        
        /// <remarks/>
        public int ProtestoQuantidade {
            get {
                return this.protestoQuantidadeField;
            }
            set {
                this.protestoQuantidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ProtestoData {
            get {
                return this.protestoDataField;
            }
            set {
                this.protestoDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ProtestoValorTotal {
            get {
                return this.protestoValorTotalField;
            }
            set {
                this.protestoValorTotalField = value;
            }
        }
        
        /// <remarks/>
        public int AcaoQuantidade {
            get {
                return this.acaoQuantidadeField;
            }
            set {
                this.acaoQuantidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> AcaoData {
            get {
                return this.acaoDataField;
            }
            set {
                this.acaoDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> AcaoValorTotal {
            get {
                return this.acaoValorTotalField;
            }
            set {
                this.acaoValorTotalField = value;
            }
        }
        
        /// <remarks/>
        public int PendenciaFinancQuantidade {
            get {
                return this.pendenciaFinancQuantidadeField;
            }
            set {
                this.pendenciaFinancQuantidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> PendenciaFinancData {
            get {
                return this.pendenciaFinancDataField;
            }
            set {
                this.pendenciaFinancDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PendenciaFinancValorTotal {
            get {
                return this.pendenciaFinancValorTotalField;
            }
            set {
                this.pendenciaFinancValorTotalField = value;
            }
        }
        
        /// <remarks/>
        public int ParticipFalenciaQuantidade {
            get {
                return this.participFalenciaQuantidadeField;
            }
            set {
                this.participFalenciaQuantidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ParticipFalenciaData {
            get {
                return this.participFalenciaDataField;
            }
            set {
                this.participFalenciaDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ParticipFalenciaValorTotal {
            get {
                return this.participFalenciaValorTotalField;
            }
            set {
                this.participFalenciaValorTotalField = value;
            }
        }
        
        /// <remarks/>
        public int SpcQuantidade {
            get {
                return this.spcQuantidadeField;
            }
            set {
                this.spcQuantidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> SpcData {
            get {
                return this.spcDataField;
            }
            set {
                this.spcDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> SpcValorTotal {
            get {
                return this.spcValorTotalField;
            }
            set {
                this.spcValorTotalField = value;
            }
        }
        
        /// <remarks/>
        public int ChequeSFQuantidade {
            get {
                return this.chequeSFQuantidadeField;
            }
            set {
                this.chequeSFQuantidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ChequeSFData {
            get {
                return this.chequeSFDataField;
            }
            set {
                this.chequeSFDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ChequeSFValorTotal {
            get {
                return this.chequeSFValorTotalField;
            }
            set {
                this.chequeSFValorTotalField = value;
            }
        }
        
        /// <remarks/>
        public int ChequeSFCCFQuantidade {
            get {
                return this.chequeSFCCFQuantidadeField;
            }
            set {
                this.chequeSFCCFQuantidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ChequeSFCCFData {
            get {
                return this.chequeSFCCFDataField;
            }
            set {
                this.chequeSFCCFDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ChequeSFCCFValorTotal {
            get {
                return this.chequeSFCCFValorTotalField;
            }
            set {
                this.chequeSFCCFValorTotalField = value;
            }
        }
        
        /// <remarks/>
        public int ChequeLojistaQuantidade {
            get {
                return this.chequeLojistaQuantidadeField;
            }
            set {
                this.chequeLojistaQuantidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ChequeLojistaData {
            get {
                return this.chequeLojistaDataField;
            }
            set {
                this.chequeLojistaDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ChequeLojistaValorTotal {
            get {
                return this.chequeLojistaValorTotalField;
            }
            set {
                this.chequeLojistaValorTotalField = value;
            }
        }
        
        /// <remarks/>
        public int ChequeCOOutrasQuantidade {
            get {
                return this.chequeCOOutrasQuantidadeField;
            }
            set {
                this.chequeCOOutrasQuantidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ChequeCOOutrasData {
            get {
                return this.chequeCOOutrasDataField;
            }
            set {
                this.chequeCOOutrasDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ChequeCOOutrasValorTotal {
            get {
                return this.chequeCOOutrasValorTotalField;
            }
            set {
                this.chequeCOOutrasValorTotalField = value;
            }
        }
        
        /// <remarks/>
        public int ConsultaRealizadaQuantidade {
            get {
                return this.consultaRealizadaQuantidadeField;
            }
            set {
                this.consultaRealizadaQuantidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ConsultaRealizadaData {
            get {
                return this.consultaRealizadaDataField;
            }
            set {
                this.consultaRealizadaDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ConsultaRealizadaValorTotal {
            get {
                return this.consultaRealizadaValorTotalField;
            }
            set {
                this.consultaRealizadaValorTotalField = value;
            }
        }
        
        /// <remarks/>
        public int AlertaDocQuantidade {
            get {
                return this.alertaDocQuantidadeField;
            }
            set {
                this.alertaDocQuantidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> AlertaDocData {
            get {
                return this.alertaDocDataField;
            }
            set {
                this.alertaDocDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> AlertaDocValorTotal {
            get {
                return this.alertaDocValorTotalField;
            }
            set {
                this.alertaDocValorTotalField = value;
            }
        }
        
        /// <remarks/>
        public int CreditoConcQuantidade {
            get {
                return this.creditoConcQuantidadeField;
            }
            set {
                this.creditoConcQuantidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CreditoConcData {
            get {
                return this.creditoConcDataField;
            }
            set {
                this.creditoConcDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> CreditoConcValorTotal {
            get {
                return this.creditoConcValorTotalField;
            }
            set {
                this.creditoConcValorTotalField = value;
            }
        }
        
        /// <remarks/>
        public int ContraOrdemQuantidade {
            get {
                return this.contraOrdemQuantidadeField;
            }
            set {
                this.contraOrdemQuantidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ContraOrdemData {
            get {
                return this.contraOrdemDataField;
            }
            set {
                this.contraOrdemDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ContraOrdemValorTotal {
            get {
                return this.contraOrdemValorTotalField;
            }
            set {
                this.contraOrdemValorTotalField = value;
            }
        }
        
        /// <remarks/>
        public int ContraOrdemDFQuantidade {
            get {
                return this.contraOrdemDFQuantidadeField;
            }
            set {
                this.contraOrdemDFQuantidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ContraOrdemDFData {
            get {
                return this.contraOrdemDFDataField;
            }
            set {
                this.contraOrdemDFDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ContraOrdemDFValorTotal {
            get {
                return this.contraOrdemDFValorTotalField;
            }
            set {
                this.contraOrdemDFValorTotalField = value;
            }
        }
        
        /// <remarks/>
        public DetalhesSpcDTO[] DetalhesSpc {
            get {
                return this.detalhesSpcField;
            }
            set {
                this.detalhesSpcField = value;
            }
        }
        
        /// <remarks/>
        public DetalhesPendenciaFinanceiraDTO[] DetalhesPendenciasFinanceiras {
            get {
                return this.detalhesPendenciasFinanceirasField;
            }
            set {
                this.detalhesPendenciasFinanceirasField = value;
            }
        }
        
        /// <remarks/>
        public DetalhesChequeLojistaDTO[] DetalhesChequesLojistas {
            get {
                return this.detalhesChequesLojistasField;
            }
            set {
                this.detalhesChequesLojistasField = value;
            }
        }
        
        /// <remarks/>
        public ContraOrdemDocumentoDiferenteDTO[] DetalhesContraOrdemDocumentoDiferente {
            get {
                return this.detalhesContraOrdemDocumentoDiferenteField;
            }
            set {
                this.detalhesContraOrdemDocumentoDiferenteField = value;
            }
        }
        
        /// <remarks/>
        public ConsultaRealizadaDTO[] DetalhesConsultasRealizadas {
            get {
                return this.detalhesConsultasRealizadasField;
            }
            set {
                this.detalhesConsultasRealizadasField = value;
            }
        }
        
        /// <remarks/>
        public AlertaDocumentosDTO[] DetalhesAlertasDocumentos {
            get {
                return this.detalhesAlertasDocumentosField;
            }
            set {
                this.detalhesAlertasDocumentosField = value;
            }
        }
        
        /// <remarks/>
        public CCFDetalhesDTO[] DetalhesCCF {
            get {
                return this.detalhesCCFField;
            }
            set {
                this.detalhesCCFField = value;
            }
        }
        
        /// <remarks/>
        public string XML {
            get {
                return this.xMLField;
            }
            set {
                this.xMLField = value;
            }
        }
        
        /// <remarks/>
        public int UsuarioId {
            get {
                return this.usuarioIdField;
            }
            set {
                this.usuarioIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum StatusAnaliseDeCreditoResponse {
        
        /// <remarks/>
        PENDENTE,
        
        /// <remarks/>
        EM_ANDAMENTO,
        
        /// <remarks/>
        EM_APROVACAO,
        
        /// <remarks/>
        APROVADO,
        
        /// <remarks/>
        REJEITADO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum TipoPessoaResponse {
        
        /// <remarks/>
        PessoaFisica,
        
        /// <remarks/>
        PessoaJuridica,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DetalhesSpcDTO {
        
        private int consultaIdField;
        
        private string associadoField;
        
        private System.DateTime inclusaoField;
        
        private System.DateTime vencimentoField;
        
        private string entidadeField;
        
        private string contratoField;
        
        private decimal valorField;
        
        /// <remarks/>
        public int ConsultaId {
            get {
                return this.consultaIdField;
            }
            set {
                this.consultaIdField = value;
            }
        }
        
        /// <remarks/>
        public string Associado {
            get {
                return this.associadoField;
            }
            set {
                this.associadoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Inclusao {
            get {
                return this.inclusaoField;
            }
            set {
                this.inclusaoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Vencimento {
            get {
                return this.vencimentoField;
            }
            set {
                this.vencimentoField = value;
            }
        }
        
        /// <remarks/>
        public string Entidade {
            get {
                return this.entidadeField;
            }
            set {
                this.entidadeField = value;
            }
        }
        
        /// <remarks/>
        public string Contrato {
            get {
                return this.contratoField;
            }
            set {
                this.contratoField = value;
            }
        }
        
        /// <remarks/>
        public decimal Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CCFDetalhesDTO {
        
        private string origemField;
        
        private System.DateTime dataUltimoChequeField;
        
        private int quantidadeField;
        
        private string motivoField;
        
        /// <remarks/>
        public string Origem {
            get {
                return this.origemField;
            }
            set {
                this.origemField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataUltimoCheque {
            get {
                return this.dataUltimoChequeField;
            }
            set {
                this.dataUltimoChequeField = value;
            }
        }
        
        /// <remarks/>
        public int Quantidade {
            get {
                return this.quantidadeField;
            }
            set {
                this.quantidadeField = value;
            }
        }
        
        /// <remarks/>
        public string Motivo {
            get {
                return this.motivoField;
            }
            set {
                this.motivoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AlertaDocumentosDTO {
        
        private System.DateTime inclusaoField;
        
        private System.DateTime ocorrenciaField;
        
        private string entidadeField;
        
        private string motivoField;
        
        private string tiposField;
        
        /// <remarks/>
        public System.DateTime Inclusao {
            get {
                return this.inclusaoField;
            }
            set {
                this.inclusaoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Ocorrencia {
            get {
                return this.ocorrenciaField;
            }
            set {
                this.ocorrenciaField = value;
            }
        }
        
        /// <remarks/>
        public string Entidade {
            get {
                return this.entidadeField;
            }
            set {
                this.entidadeField = value;
            }
        }
        
        /// <remarks/>
        public string Motivo {
            get {
                return this.motivoField;
            }
            set {
                this.motivoField = value;
            }
        }
        
        /// <remarks/>
        public string Tipos {
            get {
                return this.tiposField;
            }
            set {
                this.tiposField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultaRealizadaDTO {
        
        private string associadoField;
        
        private System.DateTime dataConsultaField;
        
        private string entidadeField;
        
        private string cidadeField;
        
        private string estadoField;
        
        /// <remarks/>
        public string Associado {
            get {
                return this.associadoField;
            }
            set {
                this.associadoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataConsulta {
            get {
                return this.dataConsultaField;
            }
            set {
                this.dataConsultaField = value;
            }
        }
        
        /// <remarks/>
        public string Entidade {
            get {
                return this.entidadeField;
            }
            set {
                this.entidadeField = value;
            }
        }
        
        /// <remarks/>
        public string Cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
            }
        }
        
        /// <remarks/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ContraOrdemDocumentoDiferenteDTO {
        
        private string documentoField;
        
        private System.DateTime inclusaoField;
        
        private System.DateTime ocorrenciaField;
        
        private string origemField;
        
        private string informanteField;
        
        private string descricaoField;
        
        /// <remarks/>
        public string Documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Inclusao {
            get {
                return this.inclusaoField;
            }
            set {
                this.inclusaoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Ocorrencia {
            get {
                return this.ocorrenciaField;
            }
            set {
                this.ocorrenciaField = value;
            }
        }
        
        /// <remarks/>
        public string Origem {
            get {
                return this.origemField;
            }
            set {
                this.origemField = value;
            }
        }
        
        /// <remarks/>
        public string Informante {
            get {
                return this.informanteField;
            }
            set {
                this.informanteField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DetalhesChequeLojistaDTO {
        
        private int consultaIdField;
        
        private string associadoField;
        
        private string entidadeField;
        
        private System.DateTime inclusaoField;
        
        private string descricaoField;
        
        private System.Nullable<System.DateTime> chequeEmissaoField;
        
        private System.Nullable<decimal> chequeValorField;
        
        private string cidadeAssociadoField;
        
        /// <remarks/>
        public int ConsultaId {
            get {
                return this.consultaIdField;
            }
            set {
                this.consultaIdField = value;
            }
        }
        
        /// <remarks/>
        public string Associado {
            get {
                return this.associadoField;
            }
            set {
                this.associadoField = value;
            }
        }
        
        /// <remarks/>
        public string Entidade {
            get {
                return this.entidadeField;
            }
            set {
                this.entidadeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Inclusao {
            get {
                return this.inclusaoField;
            }
            set {
                this.inclusaoField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ChequeEmissao {
            get {
                return this.chequeEmissaoField;
            }
            set {
                this.chequeEmissaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ChequeValor {
            get {
                return this.chequeValorField;
            }
            set {
                this.chequeValorField = value;
            }
        }
        
        /// <remarks/>
        public string CidadeAssociado {
            get {
                return this.cidadeAssociadoField;
            }
            set {
                this.cidadeAssociadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DetalhesPendenciaFinanceiraDTO {
        
        private int consultaIdField;
        
        private string tituloField;
        
        private bool avalistaField;
        
        private string contratoField;
        
        private System.DateTime ocorrenciaField;
        
        private string filialField;
        
        private string origemField;
        
        private string moedaField;
        
        private string naturezaField;
        
        private string cidadeField;
        
        private string ufField;
        
        private decimal valorField;
        
        /// <remarks/>
        public int ConsultaId {
            get {
                return this.consultaIdField;
            }
            set {
                this.consultaIdField = value;
            }
        }
        
        /// <remarks/>
        public string Titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
            }
        }
        
        /// <remarks/>
        public bool Avalista {
            get {
                return this.avalistaField;
            }
            set {
                this.avalistaField = value;
            }
        }
        
        /// <remarks/>
        public string Contrato {
            get {
                return this.contratoField;
            }
            set {
                this.contratoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Ocorrencia {
            get {
                return this.ocorrenciaField;
            }
            set {
                this.ocorrenciaField = value;
            }
        }
        
        /// <remarks/>
        public string Filial {
            get {
                return this.filialField;
            }
            set {
                this.filialField = value;
            }
        }
        
        /// <remarks/>
        public string Origem {
            get {
                return this.origemField;
            }
            set {
                this.origemField = value;
            }
        }
        
        /// <remarks/>
        public string Moeda {
            get {
                return this.moedaField;
            }
            set {
                this.moedaField = value;
            }
        }
        
        /// <remarks/>
        public string Natureza {
            get {
                return this.naturezaField;
            }
            set {
                this.naturezaField = value;
            }
        }
        
        /// <remarks/>
        public string Cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
            }
        }
        
        /// <remarks/>
        public string UF {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
        
        /// <remarks/>
        public decimal Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConsultarSPCCompletedEventHandler(object sender, ConsultarSPCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarSPCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarSPCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsultaSpcResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsultaSpcResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConsultarBancoDeDadosCompletedEventHandler(object sender, ConsultarBancoDeDadosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarBancoDeDadosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarBancoDeDadosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsultaSpcResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsultaSpcResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591