//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Ecoporto.CRM.Site.WsConsultaClientes {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Importacao_ClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback Importacao_Interna_ClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback Consulta_Importacao_ClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback Consulta_Interna_Importacao_ClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback Importacao_Cliente_V2OperationCompleted;
        
        private System.Threading.SendOrPostCallback Importacao_Interna_Cliente_V2OperationCompleted;
        
        private System.Threading.SendOrPostCallback Consulta_Importacao_Cliente_V2OperationCompleted;
        
        private System.Threading.SendOrPostCallback Consulta_Interna_Importacao_Cliente_V2OperationCompleted;
        
        private System.Threading.SendOrPostCallback SistemaSegurancaAutenticaUserOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::Ecoporto.CRM.Site.Properties.Settings.Default.Ecoporto_CRM_Site_WsConsultaClientes_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Importacao_ClienteCompletedEventHandler Importacao_ClienteCompleted;
        
        /// <remarks/>
        public event Importacao_Interna_ClienteCompletedEventHandler Importacao_Interna_ClienteCompleted;
        
        /// <remarks/>
        public event Consulta_Importacao_ClienteCompletedEventHandler Consulta_Importacao_ClienteCompleted;
        
        /// <remarks/>
        public event Consulta_Interna_Importacao_ClienteCompletedEventHandler Consulta_Interna_Importacao_ClienteCompleted;
        
        /// <remarks/>
        public event Importacao_Cliente_V2CompletedEventHandler Importacao_Cliente_V2Completed;
        
        /// <remarks/>
        public event Importacao_Interna_Cliente_V2CompletedEventHandler Importacao_Interna_Cliente_V2Completed;
        
        /// <remarks/>
        public event Consulta_Importacao_Cliente_V2CompletedEventHandler Consulta_Importacao_Cliente_V2Completed;
        
        /// <remarks/>
        public event Consulta_Interna_Importacao_Cliente_V2CompletedEventHandler Consulta_Interna_Importacao_Cliente_V2Completed;
        
        /// <remarks/>
        public event SistemaSegurancaAutenticaUserCompletedEventHandler SistemaSegurancaAutenticaUserCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Importacao_Cliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Importacao_Cliente(string CPF, string SENHA, string CNPJ_CONTA, string CNPJ_IMPORTADOR, bool APENAS_CONSULTA, string ID_USUARIO) {
            object[] results = this.Invoke("Importacao_Cliente", new object[] {
                        CPF,
                        SENHA,
                        CNPJ_CONTA,
                        CNPJ_IMPORTADOR,
                        APENAS_CONSULTA,
                        ID_USUARIO});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Importacao_ClienteAsync(string CPF, string SENHA, string CNPJ_CONTA, string CNPJ_IMPORTADOR, bool APENAS_CONSULTA, string ID_USUARIO) {
            this.Importacao_ClienteAsync(CPF, SENHA, CNPJ_CONTA, CNPJ_IMPORTADOR, APENAS_CONSULTA, ID_USUARIO, null);
        }
        
        /// <remarks/>
        public void Importacao_ClienteAsync(string CPF, string SENHA, string CNPJ_CONTA, string CNPJ_IMPORTADOR, bool APENAS_CONSULTA, string ID_USUARIO, object userState) {
            if ((this.Importacao_ClienteOperationCompleted == null)) {
                this.Importacao_ClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImportacao_ClienteOperationCompleted);
            }
            this.InvokeAsync("Importacao_Cliente", new object[] {
                        CPF,
                        SENHA,
                        CNPJ_CONTA,
                        CNPJ_IMPORTADOR,
                        APENAS_CONSULTA,
                        ID_USUARIO}, this.Importacao_ClienteOperationCompleted, userState);
        }
        
        private void OnImportacao_ClienteOperationCompleted(object arg) {
            if ((this.Importacao_ClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Importacao_ClienteCompleted(this, new Importacao_ClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Importacao_Interna_Cliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Importacao_Interna_Cliente(string CNPJ_CONTA, string CNPJ_IMPORTADOR, bool APENAS_CONSULTA, string ID_USUARIO) {
            object[] results = this.Invoke("Importacao_Interna_Cliente", new object[] {
                        CNPJ_CONTA,
                        CNPJ_IMPORTADOR,
                        APENAS_CONSULTA,
                        ID_USUARIO});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Importacao_Interna_ClienteAsync(string CNPJ_CONTA, string CNPJ_IMPORTADOR, bool APENAS_CONSULTA, string ID_USUARIO) {
            this.Importacao_Interna_ClienteAsync(CNPJ_CONTA, CNPJ_IMPORTADOR, APENAS_CONSULTA, ID_USUARIO, null);
        }
        
        /// <remarks/>
        public void Importacao_Interna_ClienteAsync(string CNPJ_CONTA, string CNPJ_IMPORTADOR, bool APENAS_CONSULTA, string ID_USUARIO, object userState) {
            if ((this.Importacao_Interna_ClienteOperationCompleted == null)) {
                this.Importacao_Interna_ClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImportacao_Interna_ClienteOperationCompleted);
            }
            this.InvokeAsync("Importacao_Interna_Cliente", new object[] {
                        CNPJ_CONTA,
                        CNPJ_IMPORTADOR,
                        APENAS_CONSULTA,
                        ID_USUARIO}, this.Importacao_Interna_ClienteOperationCompleted, userState);
        }
        
        private void OnImportacao_Interna_ClienteOperationCompleted(object arg) {
            if ((this.Importacao_Interna_ClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Importacao_Interna_ClienteCompleted(this, new Importacao_Interna_ClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Consulta_Importacao_Cliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Consulta_Importacao_Cliente(string CPF, string SENHA, string CNPJ_CONTA, string CNPJ_IMPORTADOR) {
            object[] results = this.Invoke("Consulta_Importacao_Cliente", new object[] {
                        CPF,
                        SENHA,
                        CNPJ_CONTA,
                        CNPJ_IMPORTADOR});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Consulta_Importacao_ClienteAsync(string CPF, string SENHA, string CNPJ_CONTA, string CNPJ_IMPORTADOR) {
            this.Consulta_Importacao_ClienteAsync(CPF, SENHA, CNPJ_CONTA, CNPJ_IMPORTADOR, null);
        }
        
        /// <remarks/>
        public void Consulta_Importacao_ClienteAsync(string CPF, string SENHA, string CNPJ_CONTA, string CNPJ_IMPORTADOR, object userState) {
            if ((this.Consulta_Importacao_ClienteOperationCompleted == null)) {
                this.Consulta_Importacao_ClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsulta_Importacao_ClienteOperationCompleted);
            }
            this.InvokeAsync("Consulta_Importacao_Cliente", new object[] {
                        CPF,
                        SENHA,
                        CNPJ_CONTA,
                        CNPJ_IMPORTADOR}, this.Consulta_Importacao_ClienteOperationCompleted, userState);
        }
        
        private void OnConsulta_Importacao_ClienteOperationCompleted(object arg) {
            if ((this.Consulta_Importacao_ClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Consulta_Importacao_ClienteCompleted(this, new Consulta_Importacao_ClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Consulta_Interna_Importacao_Cliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Consulta_Interna_Importacao_Cliente(string CNPJ_CONTA, string CNPJ_IMPORTADOR) {
            object[] results = this.Invoke("Consulta_Interna_Importacao_Cliente", new object[] {
                        CNPJ_CONTA,
                        CNPJ_IMPORTADOR});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Consulta_Interna_Importacao_ClienteAsync(string CNPJ_CONTA, string CNPJ_IMPORTADOR) {
            this.Consulta_Interna_Importacao_ClienteAsync(CNPJ_CONTA, CNPJ_IMPORTADOR, null);
        }
        
        /// <remarks/>
        public void Consulta_Interna_Importacao_ClienteAsync(string CNPJ_CONTA, string CNPJ_IMPORTADOR, object userState) {
            if ((this.Consulta_Interna_Importacao_ClienteOperationCompleted == null)) {
                this.Consulta_Interna_Importacao_ClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsulta_Interna_Importacao_ClienteOperationCompleted);
            }
            this.InvokeAsync("Consulta_Interna_Importacao_Cliente", new object[] {
                        CNPJ_CONTA,
                        CNPJ_IMPORTADOR}, this.Consulta_Interna_Importacao_ClienteOperationCompleted, userState);
        }
        
        private void OnConsulta_Interna_Importacao_ClienteOperationCompleted(object arg) {
            if ((this.Consulta_Interna_Importacao_ClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Consulta_Interna_Importacao_ClienteCompleted(this, new Consulta_Interna_Importacao_ClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Importacao_Cliente_V2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RespostaCliente Importacao_Cliente_V2(string CPF, string SENHA, string CNPJ_CONTA, string CNPJ_IMPORTADOR, bool APENAS_CONSULTA, string ID_USUARIO, string EMAIL_ANEXO) {
            object[] results = this.Invoke("Importacao_Cliente_V2", new object[] {
                        CPF,
                        SENHA,
                        CNPJ_CONTA,
                        CNPJ_IMPORTADOR,
                        APENAS_CONSULTA,
                        ID_USUARIO,
                        EMAIL_ANEXO});
            return ((RespostaCliente)(results[0]));
        }
        
        /// <remarks/>
        public void Importacao_Cliente_V2Async(string CPF, string SENHA, string CNPJ_CONTA, string CNPJ_IMPORTADOR, bool APENAS_CONSULTA, string ID_USUARIO, string EMAIL_ANEXO) {
            this.Importacao_Cliente_V2Async(CPF, SENHA, CNPJ_CONTA, CNPJ_IMPORTADOR, APENAS_CONSULTA, ID_USUARIO, EMAIL_ANEXO, null);
        }
        
        /// <remarks/>
        public void Importacao_Cliente_V2Async(string CPF, string SENHA, string CNPJ_CONTA, string CNPJ_IMPORTADOR, bool APENAS_CONSULTA, string ID_USUARIO, string EMAIL_ANEXO, object userState) {
            if ((this.Importacao_Cliente_V2OperationCompleted == null)) {
                this.Importacao_Cliente_V2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnImportacao_Cliente_V2OperationCompleted);
            }
            this.InvokeAsync("Importacao_Cliente_V2", new object[] {
                        CPF,
                        SENHA,
                        CNPJ_CONTA,
                        CNPJ_IMPORTADOR,
                        APENAS_CONSULTA,
                        ID_USUARIO,
                        EMAIL_ANEXO}, this.Importacao_Cliente_V2OperationCompleted, userState);
        }
        
        private void OnImportacao_Cliente_V2OperationCompleted(object arg) {
            if ((this.Importacao_Cliente_V2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Importacao_Cliente_V2Completed(this, new Importacao_Cliente_V2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Importacao_Interna_Cliente_V2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RespostaCliente Importacao_Interna_Cliente_V2(string CNPJ_CONTA, string CNPJ_IMPORTADOR, bool APENAS_CONSULTA, string ID_USUARIO, string EMAIL_ANEXO) {
            object[] results = this.Invoke("Importacao_Interna_Cliente_V2", new object[] {
                        CNPJ_CONTA,
                        CNPJ_IMPORTADOR,
                        APENAS_CONSULTA,
                        ID_USUARIO,
                        EMAIL_ANEXO});
            return ((RespostaCliente)(results[0]));
        }
        
        /// <remarks/>
        public void Importacao_Interna_Cliente_V2Async(string CNPJ_CONTA, string CNPJ_IMPORTADOR, bool APENAS_CONSULTA, string ID_USUARIO, string EMAIL_ANEXO) {
            this.Importacao_Interna_Cliente_V2Async(CNPJ_CONTA, CNPJ_IMPORTADOR, APENAS_CONSULTA, ID_USUARIO, EMAIL_ANEXO, null);
        }
        
        /// <remarks/>
        public void Importacao_Interna_Cliente_V2Async(string CNPJ_CONTA, string CNPJ_IMPORTADOR, bool APENAS_CONSULTA, string ID_USUARIO, string EMAIL_ANEXO, object userState) {
            if ((this.Importacao_Interna_Cliente_V2OperationCompleted == null)) {
                this.Importacao_Interna_Cliente_V2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnImportacao_Interna_Cliente_V2OperationCompleted);
            }
            this.InvokeAsync("Importacao_Interna_Cliente_V2", new object[] {
                        CNPJ_CONTA,
                        CNPJ_IMPORTADOR,
                        APENAS_CONSULTA,
                        ID_USUARIO,
                        EMAIL_ANEXO}, this.Importacao_Interna_Cliente_V2OperationCompleted, userState);
        }
        
        private void OnImportacao_Interna_Cliente_V2OperationCompleted(object arg) {
            if ((this.Importacao_Interna_Cliente_V2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Importacao_Interna_Cliente_V2Completed(this, new Importacao_Interna_Cliente_V2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Consulta_Importacao_Cliente_V2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RespostaCliente Consulta_Importacao_Cliente_V2(string CPF, string SENHA, string CNPJ_CONTA, string CNPJ_IMPORTADOR, string EMAIL_ANEXO) {
            object[] results = this.Invoke("Consulta_Importacao_Cliente_V2", new object[] {
                        CPF,
                        SENHA,
                        CNPJ_CONTA,
                        CNPJ_IMPORTADOR,
                        EMAIL_ANEXO});
            return ((RespostaCliente)(results[0]));
        }
        
        /// <remarks/>
        public void Consulta_Importacao_Cliente_V2Async(string CPF, string SENHA, string CNPJ_CONTA, string CNPJ_IMPORTADOR, string EMAIL_ANEXO) {
            this.Consulta_Importacao_Cliente_V2Async(CPF, SENHA, CNPJ_CONTA, CNPJ_IMPORTADOR, EMAIL_ANEXO, null);
        }
        
        /// <remarks/>
        public void Consulta_Importacao_Cliente_V2Async(string CPF, string SENHA, string CNPJ_CONTA, string CNPJ_IMPORTADOR, string EMAIL_ANEXO, object userState) {
            if ((this.Consulta_Importacao_Cliente_V2OperationCompleted == null)) {
                this.Consulta_Importacao_Cliente_V2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsulta_Importacao_Cliente_V2OperationCompleted);
            }
            this.InvokeAsync("Consulta_Importacao_Cliente_V2", new object[] {
                        CPF,
                        SENHA,
                        CNPJ_CONTA,
                        CNPJ_IMPORTADOR,
                        EMAIL_ANEXO}, this.Consulta_Importacao_Cliente_V2OperationCompleted, userState);
        }
        
        private void OnConsulta_Importacao_Cliente_V2OperationCompleted(object arg) {
            if ((this.Consulta_Importacao_Cliente_V2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Consulta_Importacao_Cliente_V2Completed(this, new Consulta_Importacao_Cliente_V2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Consulta_Interna_Importacao_Cliente_V2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RespostaCliente Consulta_Interna_Importacao_Cliente_V2(string CNPJ_CONTA, string CNPJ_IMPORTADOR, string EMAIL_ANEXO) {
            object[] results = this.Invoke("Consulta_Interna_Importacao_Cliente_V2", new object[] {
                        CNPJ_CONTA,
                        CNPJ_IMPORTADOR,
                        EMAIL_ANEXO});
            return ((RespostaCliente)(results[0]));
        }
        
        /// <remarks/>
        public void Consulta_Interna_Importacao_Cliente_V2Async(string CNPJ_CONTA, string CNPJ_IMPORTADOR, string EMAIL_ANEXO) {
            this.Consulta_Interna_Importacao_Cliente_V2Async(CNPJ_CONTA, CNPJ_IMPORTADOR, EMAIL_ANEXO, null);
        }
        
        /// <remarks/>
        public void Consulta_Interna_Importacao_Cliente_V2Async(string CNPJ_CONTA, string CNPJ_IMPORTADOR, string EMAIL_ANEXO, object userState) {
            if ((this.Consulta_Interna_Importacao_Cliente_V2OperationCompleted == null)) {
                this.Consulta_Interna_Importacao_Cliente_V2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsulta_Interna_Importacao_Cliente_V2OperationCompleted);
            }
            this.InvokeAsync("Consulta_Interna_Importacao_Cliente_V2", new object[] {
                        CNPJ_CONTA,
                        CNPJ_IMPORTADOR,
                        EMAIL_ANEXO}, this.Consulta_Interna_Importacao_Cliente_V2OperationCompleted, userState);
        }
        
        private void OnConsulta_Interna_Importacao_Cliente_V2OperationCompleted(object arg) {
            if ((this.Consulta_Interna_Importacao_Cliente_V2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Consulta_Interna_Importacao_Cliente_V2Completed(this, new Consulta_Interna_Importacao_Cliente_V2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SistemaSegurancaAutenticaUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SistemaSegurancaAutenticaUser(string CPF, string SENHA, string PRCNTR, string PRNAVIO, string PRBL, string PRFLAGMASTER) {
            object[] results = this.Invoke("SistemaSegurancaAutenticaUser", new object[] {
                        CPF,
                        SENHA,
                        PRCNTR,
                        PRNAVIO,
                        PRBL,
                        PRFLAGMASTER});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SistemaSegurancaAutenticaUserAsync(string CPF, string SENHA, string PRCNTR, string PRNAVIO, string PRBL, string PRFLAGMASTER) {
            this.SistemaSegurancaAutenticaUserAsync(CPF, SENHA, PRCNTR, PRNAVIO, PRBL, PRFLAGMASTER, null);
        }
        
        /// <remarks/>
        public void SistemaSegurancaAutenticaUserAsync(string CPF, string SENHA, string PRCNTR, string PRNAVIO, string PRBL, string PRFLAGMASTER, object userState) {
            if ((this.SistemaSegurancaAutenticaUserOperationCompleted == null)) {
                this.SistemaSegurancaAutenticaUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSistemaSegurancaAutenticaUserOperationCompleted);
            }
            this.InvokeAsync("SistemaSegurancaAutenticaUser", new object[] {
                        CPF,
                        SENHA,
                        PRCNTR,
                        PRNAVIO,
                        PRBL,
                        PRFLAGMASTER}, this.SistemaSegurancaAutenticaUserOperationCompleted, userState);
        }
        
        private void OnSistemaSegurancaAutenticaUserOperationCompleted(object arg) {
            if ((this.SistemaSegurancaAutenticaUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SistemaSegurancaAutenticaUserCompleted(this, new SistemaSegurancaAutenticaUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RespostaCliente {
        
        private string respostaField;
        
        private Arquivo[] arquivosField;
        
        /// <remarks/>
        public string Resposta {
            get {
                return this.respostaField;
            }
            set {
                this.respostaField = value;
            }
        }
        
        /// <remarks/>
        public Arquivo[] Arquivos {
            get {
                return this.arquivosField;
            }
            set {
                this.arquivosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Arquivo {
        
        private string nomeField;
        
        private string extensaoField;
        
        private byte[] dataArrayField;
        
        private string propostaField;
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string Extensao {
            get {
                return this.extensaoField;
            }
            set {
                this.extensaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] dataArray {
            get {
                return this.dataArrayField;
            }
            set {
                this.dataArrayField = value;
            }
        }
        
        /// <remarks/>
        public string Proposta {
            get {
                return this.propostaField;
            }
            set {
                this.propostaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void Importacao_ClienteCompletedEventHandler(object sender, Importacao_ClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Importacao_ClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Importacao_ClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void Importacao_Interna_ClienteCompletedEventHandler(object sender, Importacao_Interna_ClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Importacao_Interna_ClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Importacao_Interna_ClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void Consulta_Importacao_ClienteCompletedEventHandler(object sender, Consulta_Importacao_ClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Consulta_Importacao_ClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Consulta_Importacao_ClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void Consulta_Interna_Importacao_ClienteCompletedEventHandler(object sender, Consulta_Interna_Importacao_ClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Consulta_Interna_Importacao_ClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Consulta_Interna_Importacao_ClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void Importacao_Cliente_V2CompletedEventHandler(object sender, Importacao_Cliente_V2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Importacao_Cliente_V2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Importacao_Cliente_V2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespostaCliente Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespostaCliente)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void Importacao_Interna_Cliente_V2CompletedEventHandler(object sender, Importacao_Interna_Cliente_V2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Importacao_Interna_Cliente_V2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Importacao_Interna_Cliente_V2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespostaCliente Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespostaCliente)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void Consulta_Importacao_Cliente_V2CompletedEventHandler(object sender, Consulta_Importacao_Cliente_V2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Consulta_Importacao_Cliente_V2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Consulta_Importacao_Cliente_V2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespostaCliente Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespostaCliente)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void Consulta_Interna_Importacao_Cliente_V2CompletedEventHandler(object sender, Consulta_Interna_Importacao_Cliente_V2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Consulta_Interna_Importacao_Cliente_V2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Consulta_Interna_Importacao_Cliente_V2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespostaCliente Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespostaCliente)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void SistemaSegurancaAutenticaUserCompletedEventHandler(object sender, SistemaSegurancaAutenticaUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SistemaSegurancaAutenticaUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SistemaSegurancaAutenticaUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591