//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Ecoporto.CRM.Site.WsSimulador {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SimuladorCalculoSoap", Namespace="http://tempuri.org/")]
    public partial class SimuladorCalculo : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ObterTabelasOperationCompleted;
        
        private System.Threading.SendOrPostCallback CalcularTabelasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObterClienteSimuladorOperationCompleted;
        
        private System.Threading.SendOrPostCallback GerarRelatorioExcelOperationCompleted;
        
        private System.Threading.SendOrPostCallback SimuladorOportunidadeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SimuladorCalculo() {
            this.Url = global::Ecoporto.CRM.Site.Properties.Settings.Default.Ecoporto_CRM_Site_WsSimulador_SimuladorCalculo;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ObterTabelasCompletedEventHandler ObterTabelasCompleted;
        
        /// <remarks/>
        public event CalcularTabelasCompletedEventHandler CalcularTabelasCompleted;
        
        /// <remarks/>
        public event ObterClienteSimuladorCompletedEventHandler ObterClienteSimuladorCompleted;
        
        /// <remarks/>
        public event GerarRelatorioExcelCompletedEventHandler GerarRelatorioExcelCompleted;
        
        /// <remarks/>
        public event SimuladorOportunidadeCompletedEventHandler SimuladorOportunidadeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObterTabelas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Response ObterTabelas(int clienteId, string clienteCnpj, int classeCliente, int simuladorId, bool crm, bool calculoAutomatico, int tabelaId) {
            object[] results = this.Invoke("ObterTabelas", new object[] {
                        clienteId,
                        clienteCnpj,
                        classeCliente,
                        simuladorId,
                        crm,
                        calculoAutomatico,
                        tabelaId});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void ObterTabelasAsync(int clienteId, string clienteCnpj, int classeCliente, int simuladorId, bool crm, bool calculoAutomatico, int tabelaId) {
            this.ObterTabelasAsync(clienteId, clienteCnpj, classeCliente, simuladorId, crm, calculoAutomatico, tabelaId, null);
        }
        
        /// <remarks/>
        public void ObterTabelasAsync(int clienteId, string clienteCnpj, int classeCliente, int simuladorId, bool crm, bool calculoAutomatico, int tabelaId, object userState) {
            if ((this.ObterTabelasOperationCompleted == null)) {
                this.ObterTabelasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObterTabelasOperationCompleted);
            }
            this.InvokeAsync("ObterTabelas", new object[] {
                        clienteId,
                        clienteCnpj,
                        classeCliente,
                        simuladorId,
                        crm,
                        calculoAutomatico,
                        tabelaId}, this.ObterTabelasOperationCompleted, userState);
        }
        
        private void OnObterTabelasOperationCompleted(object arg) {
            if ((this.ObterTabelasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObterTabelasCompleted(this, new ObterTabelasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CalcularTabelas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Response CalcularTabelas(int simuladorId, string tabelas, bool crm) {
            object[] results = this.Invoke("CalcularTabelas", new object[] {
                        simuladorId,
                        tabelas,
                        crm});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void CalcularTabelasAsync(int simuladorId, string tabelas, bool crm) {
            this.CalcularTabelasAsync(simuladorId, tabelas, crm, null);
        }
        
        /// <remarks/>
        public void CalcularTabelasAsync(int simuladorId, string tabelas, bool crm, object userState) {
            if ((this.CalcularTabelasOperationCompleted == null)) {
                this.CalcularTabelasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalcularTabelasOperationCompleted);
            }
            this.InvokeAsync("CalcularTabelas", new object[] {
                        simuladorId,
                        tabelas,
                        crm}, this.CalcularTabelasOperationCompleted, userState);
        }
        
        private void OnCalcularTabelasOperationCompleted(object arg) {
            if ((this.CalcularTabelasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CalcularTabelasCompleted(this, new CalcularTabelasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObterClienteSimulador", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ObterClienteSimulador(int simuladorId) {
            object[] results = this.Invoke("ObterClienteSimulador", new object[] {
                        simuladorId});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ObterClienteSimuladorAsync(int simuladorId) {
            this.ObterClienteSimuladorAsync(simuladorId, null);
        }
        
        /// <remarks/>
        public void ObterClienteSimuladorAsync(int simuladorId, object userState) {
            if ((this.ObterClienteSimuladorOperationCompleted == null)) {
                this.ObterClienteSimuladorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObterClienteSimuladorOperationCompleted);
            }
            this.InvokeAsync("ObterClienteSimulador", new object[] {
                        simuladorId}, this.ObterClienteSimuladorOperationCompleted, userState);
        }
        
        private void OnObterClienteSimuladorOperationCompleted(object arg) {
            if ((this.ObterClienteSimuladorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObterClienteSimuladorCompleted(this, new ObterClienteSimuladorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GerarRelatorioExcel", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Response GerarRelatorioExcel(int simuladorId, bool comAnaliseDeDados, bool servicosComplementares, bool dadosDoCliente, bool somenteEstimativa, string dataPgtoInicial, string dataPgtoFinal, bool crm, bool vertical) {
            object[] results = this.Invoke("GerarRelatorioExcel", new object[] {
                        simuladorId,
                        comAnaliseDeDados,
                        servicosComplementares,
                        dadosDoCliente,
                        somenteEstimativa,
                        dataPgtoInicial,
                        dataPgtoFinal,
                        crm,
                        vertical});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void GerarRelatorioExcelAsync(int simuladorId, bool comAnaliseDeDados, bool servicosComplementares, bool dadosDoCliente, bool somenteEstimativa, string dataPgtoInicial, string dataPgtoFinal, bool crm, bool vertical) {
            this.GerarRelatorioExcelAsync(simuladorId, comAnaliseDeDados, servicosComplementares, dadosDoCliente, somenteEstimativa, dataPgtoInicial, dataPgtoFinal, crm, vertical, null);
        }
        
        /// <remarks/>
        public void GerarRelatorioExcelAsync(int simuladorId, bool comAnaliseDeDados, bool servicosComplementares, bool dadosDoCliente, bool somenteEstimativa, string dataPgtoInicial, string dataPgtoFinal, bool crm, bool vertical, object userState) {
            if ((this.GerarRelatorioExcelOperationCompleted == null)) {
                this.GerarRelatorioExcelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGerarRelatorioExcelOperationCompleted);
            }
            this.InvokeAsync("GerarRelatorioExcel", new object[] {
                        simuladorId,
                        comAnaliseDeDados,
                        servicosComplementares,
                        dadosDoCliente,
                        somenteEstimativa,
                        dataPgtoInicial,
                        dataPgtoFinal,
                        crm,
                        vertical}, this.GerarRelatorioExcelOperationCompleted, userState);
        }
        
        private void OnGerarRelatorioExcelOperationCompleted(object arg) {
            if ((this.GerarRelatorioExcelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GerarRelatorioExcelCompleted(this, new GerarRelatorioExcelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SimuladorOportunidade", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Response SimuladorOportunidade(int oportunidadeId, int simuladorParametroId, int modeloSimuladorId, int usuarioId) {
           object[] results = this.Invoke("SimuladorOportunidade", new object[] {
                        oportunidadeId,
                       simuladorParametroId,
                        modeloSimuladorId,
                        usuarioId});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void SimuladorOportunidadeAsync(int oportunidadeId, int simuladorParametroId, int modeloSimuladorId, int usuarioId) {
            this.SimuladorOportunidadeAsync(oportunidadeId, simuladorParametroId, modeloSimuladorId, usuarioId, null);
        }
        
        /// <remarks/>
        public void SimuladorOportunidadeAsync(int oportunidadeId, int simuladorParametroId, int modeloSimuladorId, int usuarioId, object userState) {
            if ((this.SimuladorOportunidadeOperationCompleted == null)) {
                this.SimuladorOportunidadeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSimuladorOportunidadeOperationCompleted);
            }
            this.InvokeAsync("SimuladorOportunidade", new object[] {
                        oportunidadeId,
                        simuladorParametroId,
                        modeloSimuladorId,
                        usuarioId}, this.SimuladorOportunidadeOperationCompleted, userState);
        }
        
        private void OnSimuladorOportunidadeOperationCompleted(object arg) {
            if ((this.SimuladorOportunidadeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SimuladorOportunidadeCompleted(this, new SimuladorOportunidadeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Response {
        
        private bool sucessoField;
        
        private string mensagemField;
        
        private Tabela[] listaField;
        
        private int tabelaIdField;
        
        private int arquivoIdField;
        
        private string hashField;
        
        private string nomeArquivoField;
        
        private int tamanhoArquivoField;
        
        private string base64Field;
        
        private int simuladorIdField;
        
        /// <remarks/>
        public bool Sucesso {
            get {
                return this.sucessoField;
            }
            set {
                this.sucessoField = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        public Tabela[] Lista {
            get {
                return this.listaField;
            }
            set {
                this.listaField = value;
            }
        }
        
        /// <remarks/>
        public int TabelaId {
            get {
                return this.tabelaIdField;
            }
            set {
                this.tabelaIdField = value;
            }
        }
        
        /// <remarks/>
        public int ArquivoId {
            get {
                return this.arquivoIdField;
            }
            set {
                this.arquivoIdField = value;
            }
        }
        
        /// <remarks/>
        public string Hash {
            get {
                return this.hashField;
            }
            set {
                this.hashField = value;
            }
        }
        
        /// <remarks/>
        public string NomeArquivo {
            get {
                return this.nomeArquivoField;
            }
            set {
                this.nomeArquivoField = value;
            }
        }
        
        /// <remarks/>
        public int TamanhoArquivo {
            get {
                return this.tamanhoArquivoField;
            }
            set {
                this.tamanhoArquivoField = value;
            }
        }
        
        /// <remarks/>
        public string Base64 {
            get {
                return this.base64Field;
            }
            set {
                this.base64Field = value;
            }
        }
        
        /// <remarks/>
        public int SimuladorId {
            get {
                return this.simuladorIdField;
            }
            set {
                this.simuladorIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Tabela {
        
        private int simuladorIdField;
        
        private int tabelaIdField;
        
        private string descricaoField;
        
        private string importadorField;
        
        private string despachanteField;
        
        private string nVOCCField;
        
        private string coloaderField;
        
        private string coColoaderField;
        
        private string coColoader2Field;
        
        private string propostaField;
        
        private System.DateTime dataInicioField;
        
        private System.DateTime dataFinalValidadeField;
        
        /// <remarks/>
        public int SimuladorId {
            get {
                return this.simuladorIdField;
            }
            set {
                this.simuladorIdField = value;
            }
        }
        
        /// <remarks/>
        public int TabelaId {
            get {
                return this.tabelaIdField;
            }
            set {
                this.tabelaIdField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public string Importador {
            get {
                return this.importadorField;
            }
            set {
                this.importadorField = value;
            }
        }
        
        /// <remarks/>
        public string Despachante {
            get {
                return this.despachanteField;
            }
            set {
                this.despachanteField = value;
            }
        }
        
        /// <remarks/>
        public string NVOCC {
            get {
                return this.nVOCCField;
            }
            set {
                this.nVOCCField = value;
            }
        }
        
        /// <remarks/>
        public string Coloader {
            get {
                return this.coloaderField;
            }
            set {
                this.coloaderField = value;
            }
        }
        
        /// <remarks/>
        public string CoColoader {
            get {
                return this.coColoaderField;
            }
            set {
                this.coColoaderField = value;
            }
        }
        
        /// <remarks/>
        public string CoColoader2 {
            get {
                return this.coColoader2Field;
            }
            set {
                this.coColoader2Field = value;
            }
        }
        
        /// <remarks/>
        public string Proposta {
            get {
                return this.propostaField;
            }
            set {
                this.propostaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataInicio {
            get {
                return this.dataInicioField;
            }
            set {
                this.dataInicioField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataFinalValidade {
            get {
                return this.dataFinalValidadeField;
            }
            set {
                this.dataFinalValidadeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ObterTabelasCompletedEventHandler(object sender, ObterTabelasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObterTabelasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObterTabelasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CalcularTabelasCompletedEventHandler(object sender, CalcularTabelasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CalcularTabelasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CalcularTabelasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ObterClienteSimuladorCompletedEventHandler(object sender, ObterClienteSimuladorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObterClienteSimuladorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObterClienteSimuladorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GerarRelatorioExcelCompletedEventHandler(object sender, GerarRelatorioExcelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GerarRelatorioExcelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GerarRelatorioExcelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SimuladorOportunidadeCompletedEventHandler(object sender, SimuladorOportunidadeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SimuladorOportunidadeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SimuladorOportunidadeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591