//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Ecoporto.CRM.Site.WsCalculo {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CalcularSoap", Namespace="http://tempuri.org/")]
    public partial class Calcular : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InicializarCalculoManualOperationCompleted;
        
        private System.Threading.SendOrPostCallback Atualiza_Temps_BLOperationCompleted;
        
        private System.Threading.SendOrPostCallback Calcula_GrOperationCompleted;
        
        private System.Threading.SendOrPostCallback Calcula_Impostos_BlOperationCompleted;
        
        private System.Threading.SendOrPostCallback Atualiza_VencimentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsPartLoadOperationCompleted;
        
        private System.Threading.SendOrPostCallback Valida_MinimoOperationCompleted;
        
        private System.Threading.SendOrPostCallback Verifica_LocalOperationCompleted;
        
        private System.Threading.SendOrPostCallback EferiadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback Consiste_Primeira_EntradaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Primeira_HubOperationCompleted;
        
        private System.Threading.SendOrPostCallback Forma_HubOperationCompleted;
        
        private System.Threading.SendOrPostCallback Calcula_Impostos_Desconto_RedexOperationCompleted;
        
        private System.Threading.SendOrPostCallback Calcula_Impostos_Minuta_DescontoOperationCompleted;
        
        private System.Threading.SendOrPostCallback Calcula_Impostos_DescontoOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscaIndicadorOperationCompleted;
        
        private System.Threading.SendOrPostCallback TabelaVinculadaColoaderOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Calcular() {
            this.Url = global::Ecoporto.CRM.Site.Properties.Settings.Default.Ecoporto_CRM_Site_WsCalculo_Calcular;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event InicializarCalculoManualCompletedEventHandler InicializarCalculoManualCompleted;
        
        /// <remarks/>
        public event Atualiza_Temps_BLCompletedEventHandler Atualiza_Temps_BLCompleted;
        
        /// <remarks/>
        public event Calcula_GrCompletedEventHandler Calcula_GrCompleted;
        
        /// <remarks/>
        public event Calcula_Impostos_BlCompletedEventHandler Calcula_Impostos_BlCompleted;
        
        /// <remarks/>
        public event Atualiza_VencimentoCompletedEventHandler Atualiza_VencimentoCompleted;
        
        /// <remarks/>
        public event IsPartLoadCompletedEventHandler IsPartLoadCompleted;
        
        /// <remarks/>
        public event Valida_MinimoCompletedEventHandler Valida_MinimoCompleted;
        
        /// <remarks/>
        public event Verifica_LocalCompletedEventHandler Verifica_LocalCompleted;
        
        /// <remarks/>
        public event EferiadoCompletedEventHandler EferiadoCompleted;
        
        /// <remarks/>
        public event Consiste_Primeira_EntradaCompletedEventHandler Consiste_Primeira_EntradaCompleted;
        
        /// <remarks/>
        public event Primeira_HubCompletedEventHandler Primeira_HubCompleted;
        
        /// <remarks/>
        public event Forma_HubCompletedEventHandler Forma_HubCompleted;
        
        /// <remarks/>
        public event Calcula_Impostos_Desconto_RedexCompletedEventHandler Calcula_Impostos_Desconto_RedexCompleted;
        
        /// <remarks/>
        public event Calcula_Impostos_Minuta_DescontoCompletedEventHandler Calcula_Impostos_Minuta_DescontoCompleted;
        
        /// <remarks/>
        public event Calcula_Impostos_DescontoCompletedEventHandler Calcula_Impostos_DescontoCompleted;
        
        /// <remarks/>
        public event BuscaIndicadorCompletedEventHandler BuscaIndicadorCompleted;
        
        /// <remarks/>
        public event TabelaVinculadaColoaderCompletedEventHandler TabelaVinculadaColoaderCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InicializarCalculoManual", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RetornoCalculo InicializarCalculoManual(
                    string _Lote, 
                    string _Documento, 
                    bool _PreCalculo, 
                    bool _PreCalculoLote, 
                    string _Pre_Calculo_Terminal, 
                    bool _Pre_Calculo_Ferrovia, 
                    bool _Pre_Calculo_Anvisa, 
                    bool _Pre_Calculo_HubPort, 
                    bool _Pre_Calculo_Reefer, 
                    bool _Pre_Calculo_IMO, 
                    string _Pre_Calculo_Solicitante, 
                    bool _CalcAuto, 
                    bool _CalcAverba, 
                    int _Usuario, 
                    string _DataBase, 
                    string _DataCarregamento, 
                    string _DataReefer, 
                    string _Lista, 
                    string _PreCalculoDataDesova, 
                    string _PreCalculoPesoCarga, 
                    string _PreCalculoEntrada, 
                    string _PreCalculoQtdCs, 
                    string _PreCalculoCLA, 
                    string _PreCalculoM3, 
                    bool _MargemDireita, 
                    bool _EntreMargens, 
                    bool _MargemEsquerda, 
                    string _DestinoFinal, 
                    string _LocalAtracacao, 
                    bool _DTA, 
                    bool _Ferrovia, 
                    bool _PortalFinanceiro, 
                    string _PortalFinanceiroUsuarioICC, 
                    string _Patios) {
            object[] results = this.Invoke("InicializarCalculoManual", new object[] {
                        _Lote,
                        _Documento,
                        _PreCalculo,
                        _PreCalculoLote,
                        _Pre_Calculo_Terminal,
                        _Pre_Calculo_Ferrovia,
                        _Pre_Calculo_Anvisa,
                        _Pre_Calculo_HubPort,
                        _Pre_Calculo_Reefer,
                        _Pre_Calculo_IMO,
                        _Pre_Calculo_Solicitante,
                        _CalcAuto,
                        _CalcAverba,
                        _Usuario,
                        _DataBase,
                        _DataCarregamento,
                        _DataReefer,
                        _Lista,
                        _PreCalculoDataDesova,
                        _PreCalculoPesoCarga,
                        _PreCalculoEntrada,
                        _PreCalculoQtdCs,
                        _PreCalculoCLA,
                        _PreCalculoM3,
                        _MargemDireita,
                        _EntreMargens,
                        _MargemEsquerda,
                        _DestinoFinal,
                        _LocalAtracacao,
                        _DTA,
                        _Ferrovia,
                        _PortalFinanceiro,
                        _PortalFinanceiroUsuarioICC,
                        _Patios});
            return ((RetornoCalculo)(results[0]));
        }
        
        /// <remarks/>
        public void InicializarCalculoManualAsync(
                    string _Lote, 
                    string _Documento, 
                    bool _PreCalculo, 
                    bool _PreCalculoLote, 
                    string _Pre_Calculo_Terminal, 
                    bool _Pre_Calculo_Ferrovia, 
                    bool _Pre_Calculo_Anvisa, 
                    bool _Pre_Calculo_HubPort, 
                    bool _Pre_Calculo_Reefer, 
                    bool _Pre_Calculo_IMO, 
                    string _Pre_Calculo_Solicitante, 
                    bool _CalcAuto, 
                    bool _CalcAverba, 
                    int _Usuario, 
                    string _DataBase, 
                    string _DataCarregamento, 
                    string _DataReefer, 
                    string _Lista, 
                    string _PreCalculoDataDesova, 
                    string _PreCalculoPesoCarga, 
                    string _PreCalculoEntrada, 
                    string _PreCalculoQtdCs, 
                    string _PreCalculoCLA, 
                    string _PreCalculoM3, 
                    bool _MargemDireita, 
                    bool _EntreMargens, 
                    bool _MargemEsquerda, 
                    string _DestinoFinal, 
                    string _LocalAtracacao, 
                    bool _DTA, 
                    bool _Ferrovia, 
                    bool _PortalFinanceiro, 
                    string _PortalFinanceiroUsuarioICC, 
                    string _Patios) {
            this.InicializarCalculoManualAsync(_Lote, _Documento, _PreCalculo, _PreCalculoLote, _Pre_Calculo_Terminal, _Pre_Calculo_Ferrovia, _Pre_Calculo_Anvisa, _Pre_Calculo_HubPort, _Pre_Calculo_Reefer, _Pre_Calculo_IMO, _Pre_Calculo_Solicitante, _CalcAuto, _CalcAverba, _Usuario, _DataBase, _DataCarregamento, _DataReefer, _Lista, _PreCalculoDataDesova, _PreCalculoPesoCarga, _PreCalculoEntrada, _PreCalculoQtdCs, _PreCalculoCLA, _PreCalculoM3, _MargemDireita, _EntreMargens, _MargemEsquerda, _DestinoFinal, _LocalAtracacao, _DTA, _Ferrovia, _PortalFinanceiro, _PortalFinanceiroUsuarioICC, _Patios, null);
        }
        
        /// <remarks/>
        public void InicializarCalculoManualAsync(
                    string _Lote, 
                    string _Documento, 
                    bool _PreCalculo, 
                    bool _PreCalculoLote, 
                    string _Pre_Calculo_Terminal, 
                    bool _Pre_Calculo_Ferrovia, 
                    bool _Pre_Calculo_Anvisa, 
                    bool _Pre_Calculo_HubPort, 
                    bool _Pre_Calculo_Reefer, 
                    bool _Pre_Calculo_IMO, 
                    string _Pre_Calculo_Solicitante, 
                    bool _CalcAuto, 
                    bool _CalcAverba, 
                    int _Usuario, 
                    string _DataBase, 
                    string _DataCarregamento, 
                    string _DataReefer, 
                    string _Lista, 
                    string _PreCalculoDataDesova, 
                    string _PreCalculoPesoCarga, 
                    string _PreCalculoEntrada, 
                    string _PreCalculoQtdCs, 
                    string _PreCalculoCLA, 
                    string _PreCalculoM3, 
                    bool _MargemDireita, 
                    bool _EntreMargens, 
                    bool _MargemEsquerda, 
                    string _DestinoFinal, 
                    string _LocalAtracacao, 
                    bool _DTA, 
                    bool _Ferrovia, 
                    bool _PortalFinanceiro, 
                    string _PortalFinanceiroUsuarioICC, 
                    string _Patios, 
                    object userState) {
            if ((this.InicializarCalculoManualOperationCompleted == null)) {
                this.InicializarCalculoManualOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInicializarCalculoManualOperationCompleted);
            }
            this.InvokeAsync("InicializarCalculoManual", new object[] {
                        _Lote,
                        _Documento,
                        _PreCalculo,
                        _PreCalculoLote,
                        _Pre_Calculo_Terminal,
                        _Pre_Calculo_Ferrovia,
                        _Pre_Calculo_Anvisa,
                        _Pre_Calculo_HubPort,
                        _Pre_Calculo_Reefer,
                        _Pre_Calculo_IMO,
                        _Pre_Calculo_Solicitante,
                        _CalcAuto,
                        _CalcAverba,
                        _Usuario,
                        _DataBase,
                        _DataCarregamento,
                        _DataReefer,
                        _Lista,
                        _PreCalculoDataDesova,
                        _PreCalculoPesoCarga,
                        _PreCalculoEntrada,
                        _PreCalculoQtdCs,
                        _PreCalculoCLA,
                        _PreCalculoM3,
                        _MargemDireita,
                        _EntreMargens,
                        _MargemEsquerda,
                        _DestinoFinal,
                        _LocalAtracacao,
                        _DTA,
                        _Ferrovia,
                        _PortalFinanceiro,
                        _PortalFinanceiroUsuarioICC,
                        _Patios}, this.InicializarCalculoManualOperationCompleted, userState);
        }
        
        private void OnInicializarCalculoManualOperationCompleted(object arg) {
            if ((this.InicializarCalculoManualCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InicializarCalculoManualCompleted(this, new InicializarCalculoManualCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Atualiza_Temps_BL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Atualiza_Temps_BL(long pLote) {
            object[] results = this.Invoke("Atualiza_Temps_BL", new object[] {
                        pLote});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Atualiza_Temps_BLAsync(long pLote) {
            this.Atualiza_Temps_BLAsync(pLote, null);
        }
        
        /// <remarks/>
        public void Atualiza_Temps_BLAsync(long pLote, object userState) {
            if ((this.Atualiza_Temps_BLOperationCompleted == null)) {
                this.Atualiza_Temps_BLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAtualiza_Temps_BLOperationCompleted);
            }
            this.InvokeAsync("Atualiza_Temps_BL", new object[] {
                        pLote}, this.Atualiza_Temps_BLOperationCompleted, userState);
        }
        
        private void OnAtualiza_Temps_BLOperationCompleted(object arg) {
            if ((this.Atualiza_Temps_BLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Atualiza_Temps_BLCompleted(this, new Atualiza_Temps_BLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Calcula_Gr", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Calcula_Gr(long pLote, string DataBase) {
            this.Invoke("Calcula_Gr", new object[] {
                        pLote,
                        DataBase});
        }
        
        /// <remarks/>
        public void Calcula_GrAsync(long pLote, string DataBase) {
            this.Calcula_GrAsync(pLote, DataBase, null);
        }
        
        /// <remarks/>
        public void Calcula_GrAsync(long pLote, string DataBase, object userState) {
            if ((this.Calcula_GrOperationCompleted == null)) {
                this.Calcula_GrOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalcula_GrOperationCompleted);
            }
            this.InvokeAsync("Calcula_Gr", new object[] {
                        pLote,
                        DataBase}, this.Calcula_GrOperationCompleted, userState);
        }
        
        private void OnCalcula_GrOperationCompleted(object arg) {
            if ((this.Calcula_GrCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Calcula_GrCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Calcula_Impostos_Bl", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Calcula_Impostos_Bl(string pLote, string pReeferGr, string pCalculoReefer, string pServico_Vista, string pLista, bool pPre_Calculo) {
            this.Invoke("Calcula_Impostos_Bl", new object[] {
                        pLote,
                        pReeferGr,
                        pCalculoReefer,
                        pServico_Vista,
                        pLista,
                        pPre_Calculo});
        }
        
        /// <remarks/>
        public void Calcula_Impostos_BlAsync(string pLote, string pReeferGr, string pCalculoReefer, string pServico_Vista, string pLista, bool pPre_Calculo) {
            this.Calcula_Impostos_BlAsync(pLote, pReeferGr, pCalculoReefer, pServico_Vista, pLista, pPre_Calculo, null);
        }
        
        /// <remarks/>
        public void Calcula_Impostos_BlAsync(string pLote, string pReeferGr, string pCalculoReefer, string pServico_Vista, string pLista, bool pPre_Calculo, object userState) {
            if ((this.Calcula_Impostos_BlOperationCompleted == null)) {
                this.Calcula_Impostos_BlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalcula_Impostos_BlOperationCompleted);
            }
            this.InvokeAsync("Calcula_Impostos_Bl", new object[] {
                        pLote,
                        pReeferGr,
                        pCalculoReefer,
                        pServico_Vista,
                        pLista,
                        pPre_Calculo}, this.Calcula_Impostos_BlOperationCompleted, userState);
        }
        
        private void OnCalcula_Impostos_BlOperationCompleted(object arg) {
            if ((this.Calcula_Impostos_BlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Calcula_Impostos_BlCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Atualiza_Vencimento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Atualiza_Vencimento(string DataArmazenagem, string DataReefer, bool BL_Reefer, string FormaPag, string Lote) {
            this.Invoke("Atualiza_Vencimento", new object[] {
                        DataArmazenagem,
                        DataReefer,
                        BL_Reefer,
                        FormaPag,
                        Lote});
        }
        
        /// <remarks/>
        public void Atualiza_VencimentoAsync(string DataArmazenagem, string DataReefer, bool BL_Reefer, string FormaPag, string Lote) {
            this.Atualiza_VencimentoAsync(DataArmazenagem, DataReefer, BL_Reefer, FormaPag, Lote, null);
        }
        
        /// <remarks/>
        public void Atualiza_VencimentoAsync(string DataArmazenagem, string DataReefer, bool BL_Reefer, string FormaPag, string Lote, object userState) {
            if ((this.Atualiza_VencimentoOperationCompleted == null)) {
                this.Atualiza_VencimentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAtualiza_VencimentoOperationCompleted);
            }
            this.InvokeAsync("Atualiza_Vencimento", new object[] {
                        DataArmazenagem,
                        DataReefer,
                        BL_Reefer,
                        FormaPag,
                        Lote}, this.Atualiza_VencimentoOperationCompleted, userState);
        }
        
        private void OnAtualiza_VencimentoOperationCompleted(object arg) {
            if ((this.Atualiza_VencimentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Atualiza_VencimentoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsPartLoad", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsPartLoad(string Lote) {
            object[] results = this.Invoke("IsPartLoad", new object[] {
                        Lote});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsPartLoadAsync(string Lote) {
            this.IsPartLoadAsync(Lote, null);
        }
        
        /// <remarks/>
        public void IsPartLoadAsync(string Lote, object userState) {
            if ((this.IsPartLoadOperationCompleted == null)) {
                this.IsPartLoadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsPartLoadOperationCompleted);
            }
            this.InvokeAsync("IsPartLoad", new object[] {
                        Lote}, this.IsPartLoadOperationCompleted, userState);
        }
        
        private void OnIsPartLoadOperationCompleted(object arg) {
            if ((this.IsPartLoadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsPartLoadCompleted(this, new IsPartLoadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Valida_Minimo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Valida_Minimo(int pLote, int pLista) {
            object[] results = this.Invoke("Valida_Minimo", new object[] {
                        pLote,
                        pLista});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Valida_MinimoAsync(int pLote, int pLista) {
            this.Valida_MinimoAsync(pLote, pLista, null);
        }
        
        /// <remarks/>
        public void Valida_MinimoAsync(int pLote, int pLista, object userState) {
            if ((this.Valida_MinimoOperationCompleted == null)) {
                this.Valida_MinimoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValida_MinimoOperationCompleted);
            }
            this.InvokeAsync("Valida_Minimo", new object[] {
                        pLote,
                        pLista}, this.Valida_MinimoOperationCompleted, userState);
        }
        
        private void OnValida_MinimoOperationCompleted(object arg) {
            if ((this.Valida_MinimoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Valida_MinimoCompleted(this, new Valida_MinimoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Verifica_Local", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Verifica_Local(int pLote) {
            object[] results = this.Invoke("Verifica_Local", new object[] {
                        pLote});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Verifica_LocalAsync(int pLote) {
            this.Verifica_LocalAsync(pLote, null);
        }
        
        /// <remarks/>
        public void Verifica_LocalAsync(int pLote, object userState) {
            if ((this.Verifica_LocalOperationCompleted == null)) {
                this.Verifica_LocalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerifica_LocalOperationCompleted);
            }
            this.InvokeAsync("Verifica_Local", new object[] {
                        pLote}, this.Verifica_LocalOperationCompleted, userState);
        }
        
        private void OnVerifica_LocalOperationCompleted(object arg) {
            if ((this.Verifica_LocalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Verifica_LocalCompleted(this, new Verifica_LocalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Eferiado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Eferiado(string pValor, bool pValidaDomingos) {
            object[] results = this.Invoke("Eferiado", new object[] {
                        pValor,
                        pValidaDomingos});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EferiadoAsync(string pValor, bool pValidaDomingos) {
            this.EferiadoAsync(pValor, pValidaDomingos, null);
        }
        
        /// <remarks/>
        public void EferiadoAsync(string pValor, bool pValidaDomingos, object userState) {
            if ((this.EferiadoOperationCompleted == null)) {
                this.EferiadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEferiadoOperationCompleted);
            }
            this.InvokeAsync("Eferiado", new object[] {
                        pValor,
                        pValidaDomingos}, this.EferiadoOperationCompleted, userState);
        }
        
        private void OnEferiadoOperationCompleted(object arg) {
            if ((this.EferiadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EferiadoCompleted(this, new EferiadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Consiste_Primeira_Entrada", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Consiste_Primeira_Entrada(int pLote) {
            object[] results = this.Invoke("Consiste_Primeira_Entrada", new object[] {
                        pLote});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Consiste_Primeira_EntradaAsync(int pLote) {
            this.Consiste_Primeira_EntradaAsync(pLote, null);
        }
        
        /// <remarks/>
        public void Consiste_Primeira_EntradaAsync(int pLote, object userState) {
            if ((this.Consiste_Primeira_EntradaOperationCompleted == null)) {
                this.Consiste_Primeira_EntradaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsiste_Primeira_EntradaOperationCompleted);
            }
            this.InvokeAsync("Consiste_Primeira_Entrada", new object[] {
                        pLote}, this.Consiste_Primeira_EntradaOperationCompleted, userState);
        }
        
        private void OnConsiste_Primeira_EntradaOperationCompleted(object arg) {
            if ((this.Consiste_Primeira_EntradaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Consiste_Primeira_EntradaCompleted(this, new Consiste_Primeira_EntradaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Primeira_Hub", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Primeira_Hub(long lista, long lote) {
            object[] results = this.Invoke("Primeira_Hub", new object[] {
                        lista,
                        lote});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Primeira_HubAsync(long lista, long lote) {
            this.Primeira_HubAsync(lista, lote, null);
        }
        
        /// <remarks/>
        public void Primeira_HubAsync(long lista, long lote, object userState) {
            if ((this.Primeira_HubOperationCompleted == null)) {
                this.Primeira_HubOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPrimeira_HubOperationCompleted);
            }
            this.InvokeAsync("Primeira_Hub", new object[] {
                        lista,
                        lote}, this.Primeira_HubOperationCompleted, userState);
        }
        
        private void OnPrimeira_HubOperationCompleted(object arg) {
            if ((this.Primeira_HubCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Primeira_HubCompleted(this, new Primeira_HubCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Forma_Hub", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Forma_Hub(long lista) {
            object[] results = this.Invoke("Forma_Hub", new object[] {
                        lista});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Forma_HubAsync(long lista) {
            this.Forma_HubAsync(lista, null);
        }
        
        /// <remarks/>
        public void Forma_HubAsync(long lista, object userState) {
            if ((this.Forma_HubOperationCompleted == null)) {
                this.Forma_HubOperationCompleted = new System.Threading.SendOrPostCallback(this.OnForma_HubOperationCompleted);
            }
            this.InvokeAsync("Forma_Hub", new object[] {
                        lista}, this.Forma_HubOperationCompleted, userState);
        }
        
        private void OnForma_HubOperationCompleted(object arg) {
            if ((this.Forma_HubCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Forma_HubCompleted(this, new Forma_HubCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Calcula_Impostos_Desconto_Redex", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Calcula_Impostos_Desconto_Redex(long Booking, long Servico, double ValorDesconto, double Seqgr, long ClienteId, long TabelaId, long SolicitacaoId) {
            object[] results = this.Invoke("Calcula_Impostos_Desconto_Redex", new object[] {
                        Booking,
                        Servico,
                        ValorDesconto,
                        Seqgr,
                        ClienteId,
                        TabelaId,
                        SolicitacaoId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Calcula_Impostos_Desconto_RedexAsync(long Booking, long Servico, double ValorDesconto, double Seqgr, long ClienteId, long TabelaId, long SolicitacaoId) {
            this.Calcula_Impostos_Desconto_RedexAsync(Booking, Servico, ValorDesconto, Seqgr, ClienteId, TabelaId, SolicitacaoId, null);
        }
        
        /// <remarks/>
        public void Calcula_Impostos_Desconto_RedexAsync(long Booking, long Servico, double ValorDesconto, double Seqgr, long ClienteId, long TabelaId, long SolicitacaoId, object userState) {
            if ((this.Calcula_Impostos_Desconto_RedexOperationCompleted == null)) {
                this.Calcula_Impostos_Desconto_RedexOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalcula_Impostos_Desconto_RedexOperationCompleted);
            }
            this.InvokeAsync("Calcula_Impostos_Desconto_Redex", new object[] {
                        Booking,
                        Servico,
                        ValorDesconto,
                        Seqgr,
                        ClienteId,
                        TabelaId,
                        SolicitacaoId}, this.Calcula_Impostos_Desconto_RedexOperationCompleted, userState);
        }
        
        private void OnCalcula_Impostos_Desconto_RedexOperationCompleted(object arg) {
            if ((this.Calcula_Impostos_Desconto_RedexCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Calcula_Impostos_Desconto_RedexCompleted(this, new Calcula_Impostos_Desconto_RedexCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Calcula_Impostos_Minuta_Desconto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Calcula_Impostos_Minuta_Desconto(long Minuta, long Servico, double ValorDesconto, long SolicitacaoId) {
            object[] results = this.Invoke("Calcula_Impostos_Minuta_Desconto", new object[] {
                        Minuta,
                        Servico,
                        ValorDesconto,
                        SolicitacaoId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Calcula_Impostos_Minuta_DescontoAsync(long Minuta, long Servico, double ValorDesconto, long SolicitacaoId) {
            this.Calcula_Impostos_Minuta_DescontoAsync(Minuta, Servico, ValorDesconto, SolicitacaoId, null);
        }
        
        /// <remarks/>
        public void Calcula_Impostos_Minuta_DescontoAsync(long Minuta, long Servico, double ValorDesconto, long SolicitacaoId, object userState) {
            if ((this.Calcula_Impostos_Minuta_DescontoOperationCompleted == null)) {
                this.Calcula_Impostos_Minuta_DescontoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalcula_Impostos_Minuta_DescontoOperationCompleted);
            }
            this.InvokeAsync("Calcula_Impostos_Minuta_Desconto", new object[] {
                        Minuta,
                        Servico,
                        ValorDesconto,
                        SolicitacaoId}, this.Calcula_Impostos_Minuta_DescontoOperationCompleted, userState);
        }
        
        private void OnCalcula_Impostos_Minuta_DescontoOperationCompleted(object arg) {
            if ((this.Calcula_Impostos_Minuta_DescontoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Calcula_Impostos_Minuta_DescontoCompleted(this, new Calcula_Impostos_Minuta_DescontoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Calcula_Impostos_Desconto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Calcula_Impostos_Desconto(long Lote, long Servico, double ValorDesconto, long SeqGR, long IdTabela, long SolicitacaoId) {
            object[] results = this.Invoke("Calcula_Impostos_Desconto", new object[] {
                        Lote,
                        Servico,
                        ValorDesconto,
                        SeqGR,
                        IdTabela,
                        SolicitacaoId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Calcula_Impostos_DescontoAsync(long Lote, long Servico, double ValorDesconto, long SeqGR, long IdTabela, long SolicitacaoId) {
            this.Calcula_Impostos_DescontoAsync(Lote, Servico, ValorDesconto, SeqGR, IdTabela, SolicitacaoId, null);
        }
        
        /// <remarks/>
        public void Calcula_Impostos_DescontoAsync(long Lote, long Servico, double ValorDesconto, long SeqGR, long IdTabela, long SolicitacaoId, object userState) {
            if ((this.Calcula_Impostos_DescontoOperationCompleted == null)) {
                this.Calcula_Impostos_DescontoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalcula_Impostos_DescontoOperationCompleted);
            }
            this.InvokeAsync("Calcula_Impostos_Desconto", new object[] {
                        Lote,
                        Servico,
                        ValorDesconto,
                        SeqGR,
                        IdTabela,
                        SolicitacaoId}, this.Calcula_Impostos_DescontoOperationCompleted, userState);
        }
        
        private void OnCalcula_Impostos_DescontoOperationCompleted(object arg) {
            if ((this.Calcula_Impostos_DescontoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Calcula_Impostos_DescontoCompleted(this, new Calcula_Impostos_DescontoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscaIndicador", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long BuscaIndicador(long Importador, long Despachante, long Lote, byte grava) {
            object[] results = this.Invoke("BuscaIndicador", new object[] {
                        Importador,
                        Despachante,
                        Lote,
                        grava});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void BuscaIndicadorAsync(long Importador, long Despachante, long Lote, byte grava) {
            this.BuscaIndicadorAsync(Importador, Despachante, Lote, grava, null);
        }
        
        /// <remarks/>
        public void BuscaIndicadorAsync(long Importador, long Despachante, long Lote, byte grava, object userState) {
            if ((this.BuscaIndicadorOperationCompleted == null)) {
                this.BuscaIndicadorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscaIndicadorOperationCompleted);
            }
            this.InvokeAsync("BuscaIndicador", new object[] {
                        Importador,
                        Despachante,
                        Lote,
                        grava}, this.BuscaIndicadorOperationCompleted, userState);
        }
        
        private void OnBuscaIndicadorOperationCompleted(object arg) {
            if ((this.BuscaIndicadorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscaIndicadorCompleted(this, new BuscaIndicadorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TabelaVinculadaColoader", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long TabelaVinculadaColoader(long Lote, int ClienteLogado, int Grava, int Importador, int Indicador, int CargaPatio, bool Pre_Calculo_Lote) {
            object[] results = this.Invoke("TabelaVinculadaColoader", new object[] {
                        Lote,
                        ClienteLogado,
                        Grava,
                        Importador,
                        Indicador,
                        CargaPatio,
                        Pre_Calculo_Lote});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void TabelaVinculadaColoaderAsync(long Lote, int ClienteLogado, int Grava, int Importador, int Indicador, int CargaPatio, bool Pre_Calculo_Lote) {
            this.TabelaVinculadaColoaderAsync(Lote, ClienteLogado, Grava, Importador, Indicador, CargaPatio, Pre_Calculo_Lote, null);
        }
        
        /// <remarks/>
        public void TabelaVinculadaColoaderAsync(long Lote, int ClienteLogado, int Grava, int Importador, int Indicador, int CargaPatio, bool Pre_Calculo_Lote, object userState) {
            if ((this.TabelaVinculadaColoaderOperationCompleted == null)) {
                this.TabelaVinculadaColoaderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTabelaVinculadaColoaderOperationCompleted);
            }
            this.InvokeAsync("TabelaVinculadaColoader", new object[] {
                        Lote,
                        ClienteLogado,
                        Grava,
                        Importador,
                        Indicador,
                        CargaPatio,
                        Pre_Calculo_Lote}, this.TabelaVinculadaColoaderOperationCompleted, userState);
        }
        
        private void OnTabelaVinculadaColoaderOperationCompleted(object arg) {
            if ((this.TabelaVinculadaColoaderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TabelaVinculadaColoaderCompleted(this, new TabelaVinculadaColoaderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RetornoCalculo {
        
        private bool sucessoField;
        
        private string mensagemField;
        
        private int ultimoCalculoField;
        
        /// <remarks/>
        public bool Sucesso {
            get {
                return this.sucessoField;
            }
            set {
                this.sucessoField = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        public int UltimoCalculo {
            get {
                return this.ultimoCalculoField;
            }
            set {
                this.ultimoCalculoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void InicializarCalculoManualCompletedEventHandler(object sender, InicializarCalculoManualCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InicializarCalculoManualCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InicializarCalculoManualCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RetornoCalculo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RetornoCalculo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Atualiza_Temps_BLCompletedEventHandler(object sender, Atualiza_Temps_BLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Atualiza_Temps_BLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Atualiza_Temps_BLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Calcula_GrCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Calcula_Impostos_BlCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Atualiza_VencimentoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void IsPartLoadCompletedEventHandler(object sender, IsPartLoadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsPartLoadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsPartLoadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Valida_MinimoCompletedEventHandler(object sender, Valida_MinimoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Valida_MinimoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Valida_MinimoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Verifica_LocalCompletedEventHandler(object sender, Verifica_LocalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Verifica_LocalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Verifica_LocalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EferiadoCompletedEventHandler(object sender, EferiadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EferiadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EferiadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Consiste_Primeira_EntradaCompletedEventHandler(object sender, Consiste_Primeira_EntradaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Consiste_Primeira_EntradaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Consiste_Primeira_EntradaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Primeira_HubCompletedEventHandler(object sender, Primeira_HubCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Primeira_HubCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Primeira_HubCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Forma_HubCompletedEventHandler(object sender, Forma_HubCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Forma_HubCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Forma_HubCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Calcula_Impostos_Desconto_RedexCompletedEventHandler(object sender, Calcula_Impostos_Desconto_RedexCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Calcula_Impostos_Desconto_RedexCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Calcula_Impostos_Desconto_RedexCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Calcula_Impostos_Minuta_DescontoCompletedEventHandler(object sender, Calcula_Impostos_Minuta_DescontoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Calcula_Impostos_Minuta_DescontoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Calcula_Impostos_Minuta_DescontoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Calcula_Impostos_DescontoCompletedEventHandler(object sender, Calcula_Impostos_DescontoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Calcula_Impostos_DescontoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Calcula_Impostos_DescontoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void BuscaIndicadorCompletedEventHandler(object sender, BuscaIndicadorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscaIndicadorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscaIndicadorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void TabelaVinculadaColoaderCompletedEventHandler(object sender, TabelaVinculadaColoaderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TabelaVinculadaColoaderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TabelaVinculadaColoaderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591